### ISSUE TITLE
if no devices, should offer to add them

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#1]
Now if no devices, showed label "Requested devices do not exist". 
User dont make any requests!
This message is misleading, should offer to add devices.
![2015-05-28 0 01 00](https://cloud.githubusercontent.com/assets/2894860/7847641/63d49ea2-04cd-11e5-98a8-6e7e261c0f78.png)

**Comment by vades** [comment]
New message: There are no devices installed + link to Include device
![elements-nodevices](https://cloud.githubusercontent.com/assets/1451741/8202521/0f74ce36-14db-11e5-8ffd-798c0578f3ee.png)

**Comment by PoltoS** [comment]
Note that new backend sneds 200 OK with [] instead of 404 on no devices
