### ISSUE TITLE
If widget don't receive status of device, the buttons is unchecked

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#10]
My code device used only command "on" and "off", and do not get status. I think widgets don't know status, so both the buttons is unchecked  
![2015-06-05 19 06 10](https://cloud.githubusercontent.com/assets/2894860/8010136/52b22870-0bb6-11e5-8000-359de0fb3198.png)

**Comment by PoltoS** [comment]
А теперь ещё раз на русском

**Comment by aivs** [comment]
Такая тема, создал Code Device, назначил команду Off и команду On, но не задал команду для опроса, кнопочки не имеют рамки, вообще с кнопками есть и другие проблемы, я создал для них изуеся

**Comment by vades** [comment]
Sometimes is in polling data "level: undefined"
...the buttons are unchecked: That's normal behaviour.
