### ISSUE TITLE
Trap events functionality lost after upgrade to v2.2.0

### ISSUE THREAD

**Issue by NicolasRT** [Z-Wave-Me/zwave-smarthome#100]
I was sucessfully using during months the "Trap events from Remotes and Sensors " app with an aeonlab minimote and with an aeotec keyfob. 
Since the server has been upgraded (v2.1.1 t0 v2.2.0), keys pressed on these remotes are not able to initiate actions. 
The problem  is that IF->THEN app used to associate the remote buttons to "code device" apps is not possible anymore :
- After upgrade, fields are empty in the  IF->THEN app used for remotes.
- It is also impossible to associate the IF field to one of the trapped remote button (they are no more available in the list).

**Comment by pz1** [comment]
This afternoon I just set something like that up in the latest release v2.2.1. That works fine for me for some 4 hours now.
I am updating an older [topic about that installation](http://forum.z-wave.me/viewtopic.php?f=3424&t=21965) in the forum Recipes section. I hope to finish that with more detail on the individual settings some time tomorrow. In my set up I do use ZME_WALLC_S wall controller, from which one "switch" is operated by direct association. The other operates an outside light on RaspberryPi in an adjacent building

**Comment by ronie-z-wave** [comment]
Please update to v2.2.1. 

Known issues like:
- broken IF>Then
- issues with selecting devices in apps

were already solved in that version.

**Comment by NicolasRT** [comment]
Hi all,
thanks for your work, but after upgrading to v2.2.1, IF-THEN associations related to my 2 remotes (minimote and keyfob) are again broken and no more access to the trapped buttons ...

**Comment by pz1** [comment]
I did install the new version v2.2.3-rc2. Unfortunately this Trap Events App that was working for me in 2.2.1, wasn't working anymore after this upgrade.
