### ISSUE TITLE
In module Code Device cant set polling time 1 second for Binary Switch and Sensor

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#102]
In module Code Device if you choose Sensor Binary or Switch Binary you cant set polling time 1 seconds. If you press Save button, field becomes empty. In config I see 0.
For multilevel sensor and switch all ok.

**Comment by PoltoS** [comment]
Seems to be related to this fix: https://github.com/Z-Wave-Me/home-automation/commit/c65975d3b07cfc98c00927cda4105968f3ca169c

Please config,
