### ISSUE TITLE
[webif]

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#103]
[Not a SH UI issue, but for webif]:
May be we should add such a help in webif page help? (see my comment)

http://forum.z-wave.me/viewtopic.php?f=3422&t=22911&p=61108#p61108

**Comment by pz1** [comment]
Presently the WebIF when not available has a very non-informative content:
> Webif is switched off. You can switch it on from Z-Way UI or box shell

I would expect to have a box that I can check in the Administrator menu, but it isn't. There are no clues for the average user how to tackle this.

**Comment by pz1** [comment]
In v2.2.2-rc7 there is still the same text, only font size has been slightly reduced
