### ISSUE TITLE
remote access password window is broken in 2.2.1 release.

### ISSUE THREAD

**Issue by NilsBohr** [Z-Wave-Me/zwave-smarthome#105]
Unfortunatelly remote access pasword window is not shown on the latest 2.2.1 release.

Nowhere to write the password.

![image](https://cloud.githubusercontent.com/assets/5468659/13316360/c6a75464-dbc0-11e5-90c7-f0e23fb2e91c.png)

**Comment by ronie-z-wave** [comment]
Now it is possible to login with your sh ui login and password via remote. 
Only access id is necessary to do this:

e.g. on https://find.z-wave.me/ you can now login with:

Z-Box ID: 34564/SH-LOGIN
Password: SH-PASSWORD

Means a different pw for remote access isn't necessary anymore. Seems that we've missed to communicate this in release notes ...
