### ISSUE TITLE
Trap events functionality lost after upgrade to v2.2.1 (see also issue #100)

### ISSUE THREAD

**Issue by NicolasRT** [Z-Wave-Me/zwave-smarthome#106]
Hi all,
after upgrading to v2.2.1, IF-THEN associations related to my 2 remotes (minimote and keyfob) are again broken and no more access to the trapped buttons ...

**Comment by ronie-z-wave** [comment]
Hi NicolasRT,

could you please check if these trapped buttons are availabe in namespaces API?

http://YOURRASP:8083/ZAutomation/api/v1/namespaces/devices_toggleButton
http://YOURRASP:8083/ZAutomation/api/v1/namespaces/devices_switchControl

If not, please go for sure that the devices are really included and search them in:

Menu > Devices > z-wave Manage > Z-Wave devices or go to 
http://YOURRASP:8083/smarthome/#/zwave/devices

If yes, go to Menu > Apps > Apps active and **remove** 'Trap events from Remotes and Sensors' instance. Then add it again via Local Apps - no configuration should be necessary.

If buttons were not generated automatically, please press the buttons on your remotes to force that.
After that please check the namespaces and the If>Then app again.

If this won't help a look at your event list (left icon in toolbar) filtered by system or errors and your z-way-server.log (ssh to you box - /var/log/z-way-server.log) would be helpful.

**Comment by NicolasRT** [comment]
http://YOURRASP:8083/ZAutomation/api/v1/namespaces/devices_toggleButton
gives that :
{"data":[{"deviceId":"LightScene_5","deviceName":"Scene ON Chemin Cellier"},{"deviceId":"LightScene_7","deviceName":"Scene OFF Chemin Cellier"},{"deviceId":"LightScene_74","deviceName":"Light Scene TNT"},{"deviceId":"LightScene_78","deviceName":"Volet chambre full open"},{"deviceId":"LightScene_79","deviceName":"Volet Chambre Pare Soleil"},{"deviceId":"LightScene_80","deviceName":"Volet Chambre Full closed"},{"deviceId":"Code_Device_toggleButton_9","deviceName":"Code Minimote 4 Court"},{"deviceId":"Code_Device_toggleButton_13","deviceName":"Code descente volet cuisine"},{"deviceId":"Code_Device_toggleButton_14","deviceName":"Code montée volet cuisine"},{"deviceId":"Code_Device_toggleButton_15","deviceName":"Volet Cuisine 90%"},{"deviceId":"Code_Device_toggleButton_17","deviceName":"Volet Cuisine 50%"},{"deviceId":"Code_Device_toggleButton_20","deviceName":"Code Tous extérieurs"},{"deviceId":"Code_Device_toggleButton_27","deviceName":"Code Notification Garage"},{"deviceId":"Code_Device_toggleButton_63","deviceName":"Extinction TNT"},{"deviceId":"Code_Device_toggleButton_68","deviceName":"Code device Escalier"}],"code":200,"message":"200 OK","error":null}

http://YOURRASP:8083/ZAutomation/api/v1/namespaces/devices_switchControl
gives that :
{"data":null,"code":404,"message":"404 Not Found","error":"No namespaces found with this path: devices_switchControl"}

http://YOURRASP:8083/smarthome/#/zwave/devices :
shows my remotes and the other devices
![1](https://cloud.githubusercontent.com/assets/14308982/13354491/a30450d0-dc9b-11e5-81d3-f7dcdbd4ee30.jpg)

Doing that : 
Menu > Apps > Apps active and remove 'Trap events from Remotes and Sensors' instance. Then add it again via Local Apps - no configuration should be necessary.
Gives that :
The old trapped buttons dissapeared. I created new ones by pressing the remote buttons (visible in the elements list), but no way to make association in a IF->THEN because these new buttons are never visible there....


Here a piece of my logfile : 
[z-way-server.txt](https://github.com/Z-Wave-Me/zwave-smarthome/files/148312/z-way-server.txt)

**Comment by ronie-z-wave** [comment]
Hi,
which version of the Aeotec Key Fob and Minimote are you using? 

I've tested it on rpi with v2.2.1 with Aeotec Key Fob Gen5 and Minimote FW v1.19.

Because the devices comes not with 'CentralScene' commando class by default it is necessary to add the buttons/scenes manually after inclusion.

I got 8 buttons for each device and could see/choose them all in IF->Then App. Also the created If->Then associations worked fine.

Your output looks ok. Also 404 is ok, because you have no devices with type 'switchControl' included - scenes were rendered as toggleButtons.

http://YOURRASP:8083/ZAutomation/api/v1/namespaces/devices_toggleButton

This api is used in dropdown of If->Then for scenes ... so if they are in it, it should usually work.

What about:

http://YOURRASP:8083/ZAutomation/api/v1/namespaces/devices_toggleButton.deviceId
http://YOURRASP:8083/ZAutomation/api/v1/namespaces/devices_toggleButton.deviceName

Is your version of If->Then also up to date (2.0.5)?
Maybe it is also necessary to recreate the If->Then instances - means remove them completely and recreated them.

**Comment by NicolasRT** [comment]
Dear Ronie,
many thanks for your answer.
The minimote is with the 1.19
The aeotec KeyFob is with the 1.14
As it was not working with V2.2.1, I'm still using the v2.1.1 of zway smarthome, thus The If->Then App is 1.0.0. My remotes work fine with this older version and I need them,  but I would also be verry happy to use the new functionnalities I saw in v2.2.1!
I will try again the v2.2.1 but I think I've already tried to recreate the IF->Then without success. I will let you know.

**Comment by zwave-mke** [comment]
Hello,
is this issue fixed?

**Comment by NicolasRT** [comment]
Dear Ronie,
I managed to have the v2.2.1 working fine after new installation of the raspbian and the z-way software. It means also that I had to reconfigure all my automation rule, It has been really fastidious. It means also that I don't dare anymore to upgrade the zway software. So the answer to your question is yes and No. It works but I had to redo everything.
