### ISSUE TITLE
Remember me causes infinite loop after SW restart

### ISSUE THREAD

**Issue by NilsBohr** [Z-Wave-Me/zwave-smarthome#108]
Version SW: 2.2.1

Steps to reproduce:

- launch SW
- put mark "remember me"
![image](https://cloud.githubusercontent.com/assets/5468659/13393870/35c202cc-def5-11e5-9fb4-93f2db8cd549.png)

- login
- restart SW: 
`sudo /etc/init.d/z-way-server restart`
- try to open page
![image](https://cloud.githubusercontent.com/assets/5468659/13394744/6cd46c5e-defb-11e5-8dc8-70f34fb00951.png)

Infinite loop started

**Comment by vades** [comment]
Fixed - "Fix for logout loop #108"
