### ISSUE TITLE
v2.2.2-rc2: Some itches

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#118]
1) Removed Apps are not removed from Dashboard
![capture](https://cloud.githubusercontent.com/assets/7747627/14013506/2243e934-f1ad-11e5-97bf-d110d33f8fd7.PNG)
2) The vDev configuration menu no longer displays the Element ID that was there before like in 2.2.1
![somfy](https://cloud.githubusercontent.com/assets/7747627/14013696/1f0bc56a-f1ae-11e5-90d1-a691dc6cb24b.PNG)
:

**Comment by pz1** [comment]
Never been served so fast ;) Thanks
I'll close the issue when I see it in next release.

**Comment by pz1** [comment]
One more. Why do some vDevs (binary/multilevel-switches?) have a grey circle around the image? noticed it in this release, but I just saw it is also in v2.2.1. Not so nice if one uses non-standard icons:
![som2](https://cloud.githubusercontent.com/assets/7747627/14018913/70fd5c72-f1d0-11e5-87e6-5c7e55abed60.PNG)

**Comment by vades** [comment]
By clicking on the icon with grey circle user can send an update command "device_id/command/update"
