### ISSUE TITLE
Feature Request: Incorporation of EUI Status info in Battery Status Screen

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#119]
For me, the most often used function of EUI is the status menu (/expert/#/device/status). There I am mostly interested in the battery driven devices.

So I suggest to add the EUI status columns: *Sleeping, Awake, Date* to the Smarthome  Devices/ZwaveManage/Battery Status screen

**Comment by vades** [comment]
Done
![battery-status](https://cloud.githubusercontent.com/assets/1451741/16334632/659e9c04-3a02-11e6-9812-449cc11f5f20.png)

**Comment by pz1** [comment]
Great! thanks
I'll wait for the next solid RC tot test this.

**Comment by pz1** [comment]
Just checked works fine
