### ISSUE TITLE
Add description below title on the app

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#123]
1) Place for title very short, App names not fit.
2) Good idea to add description below title on the app. A lot of modules, and open each and read the description very tiring.

DoorLock App with description:
![title_with_description](https://cloud.githubusercontent.com/assets/2894860/14282877/48ca79d8-fb49-11e5-899a-081921c1b422.png)

DoorLock App without description:
![2016-04-05 15 53 54](https://cloud.githubusercontent.com/assets/2894860/14282873/38a7b016-fb49-11e5-8f5a-3e30b1b71591.png)

**Comment by PoltoS** [comment]
I support this
