### ISSUE TITLE
Add button "Add device" to dashboard if no devices

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#124]
I think good idea to add button "Add device" to dashboard if count of Z-Wave devices zero, something like this.
<img width="1012" alt="2016-04-06 13 39 44" src="https://cloud.githubusercontent.com/assets/2894860/14314037/b89b8b58-fbfd-11e5-8876-380931f01ac3.png">

**Comment by zwave-mke** [comment]
is in progress for 2.2.2 ;)
