### ISSUE TITLE
userModule icon distorted

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#14]
This realy is a minor problem. Just wanted to inform you.
In one of my userModules I do use this [icon.png](https://github.com/pz1/home-automation/blob/develop/userModules/SolQoS/htdocs/icon.png) with dimensions 31*58 pixels. It is an image for a solar panel. In the list of modules it does not fit nicely in the framwork as you can see here:
![scaling issue](https://cloud.githubusercontent.com/assets/7747627/8251764/9d5ef2bc-167f-11e5-93df-1b58587183b3.PNG)
In the http://IP:8083/smarthome/#/elements section the icon is also used by the module itself to represent four different statusses. There it fits nicely in a round cut-out:
![roundedicon](https://cloud.githubusercontent.com/assets/7747627/8252014/c4e4adf2-1681-11e5-8e32-607b5a16234e.PNG)

**Comment by vades** [comment]
Icons should be designed as a square (e.g: 58*58 px). If your icon is not a square, place it on sqare white bacground (Photoshop. Gimp..) and save it.

**Comment by pz1** [comment]
Thanks
