### ISSUE TITLE
Add update time to toggle button

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#167]
Device with CentralScene like Fibaro Swipe perfectly works with module Trap Events, but on toggle widget I can't see when Swipe send command, please add update time like a sensors.
<img width="1195" alt="2016-06-03 22 51 36" src="https://cloud.githubusercontent.com/assets/2894860/15791058/d4aedd3c-29dd-11e6-82c9-8585b5064e3d.png">

**Comment by vades** [comment]
How to recognize a device with the CentralScene?

**Comment by PoltoS** [comment]
@aivs just suggests to add timestamp (lastupdate) to these devices to see last click time. May be it is worth to do on all devices, but make it visible only on mouse over.

Or add sort of devices "by last update". This will help too.

Or both ;) Anyway, this is minor, there is notification log to see these things. Right?

**Comment by vades** [comment]
Done
