### ISSUE TITLE
Incorrect sort of namespaces in Alpaca pre-process

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#168]
Here is the output of http://192.168.0.32:8083/ZAutomation/api/v1/modules/ToggleDevices?lang=en:

{
    "data": {
        ....
        "schema": {
            "type": "object",
            "properties": {
                "toggleDevice": {....},
                "targetDevices": {
                    "type": "array",
                    "items": {
                        "field": "enum",
                        "datasource": "namespaces",
                        "enum": [
                            "ZWayVDev_zway_3-0-37",
                            "ZWayVDev_zway_6-0-37",
                            "ZWayVDev_zway_8-0-37",
                            "ZWayVDev_zway_11-1-37",
                            "ZWayVDev_zway_11-2-37",
                            "ZWayVDev_zway_14-0-37",
                            "ZWayVDev_zway_23-0-37",
                            "ZWayVDev_zway_24-0-37",
                            "ZWayVDev_zway_25-0-37",
                            "ZWayVDev_zway_30-0-37",
                            "ZWayVDev_zway_45-0-37",
                            "ZWayVDev_zway_50-0-37",
                            "ZWayVDev_zway1_3-0-37",
                            "ZWayVDev_zway1_3-1-37",
                            "ZWayVDev_zway1_3-2-37",
                            "ZWayVDev_zway1_6-0-37",
                            "ZWayVDev_zway_2-0-38",
                            "ZWayVDev_zway_5-0-38",
                            "ZWayVDev_zway_12-0-38",
                            "ZWayVDev_zway_28-0-38"
                        ],
                       ...
                    }
                }
            }
        },
        "options": {
            "fields": {
                "toggleDevice": {...},
                "targetDevices": {
                    "label": "Devices to toggle:",
                    "fields": {
                        "item": {
                            "type": "select",
                            "datasource": "namespaces",
                            "field": "optionLabels",
                            "optionLabels": [
                                "Подсветка в ванной",
                                "Свет в балке",
                                "Свет в ванной",
                                "Нижняя лампа на куне",
                                "Верхняя лампа на кухне",
                                "Свет в спальне",
                                "Вентилятор в ванной",
                                "Switch 24:0",
                                "Вентилятор в туалете",
                                "Подсветка кухни",
                                "Розетка",
                                "Свет в спальне над кроватью",
                                "Z-Wave.Me Switch (3.0)",
                                "Свет в коридоре",
                                "Z-Wave.Me Switch (3.2)",
                                "Свет в детской",
                                "Свет в гостиной",
                                "Свет в кабинете",
                                "Свет в туалете"
                            ]
                        }
.....
}

But the select items are sorted incorrectly
`<select id="alpaca11" name="targetDevices_0" class="alpaca-control form-control">
        <option value="ZWayVDev_zway_24-0-37">Switch 24:0</option>
        <option value="ZWayVDev_zway1_3-0-37">Z-Wave.Me Switch (3.0)</option>
        <option value="ZWayVDev_zway1_3-2-37">Z-Wave.Me Switch (3.2)</option>
        <option value="ZWayVDev_zway_28-0-38">ZWayVDev_zway_28-0-38</option>
        <option value="ZWayVDev_zway_23-0-37">Вентилятор в ванной</option>
        <option value="ZWayVDev_zway_25-0-37">Вентилятор в туалете</option>
        <option value="ZWayVDev_zway_11-2-37">Верхняя лампа на кухне</option>
        <option value="ZWayVDev_zway_11-1-37">Нижняя лампа на куне</option>
        <option value="ZWayVDev_zway_3-0-37">Подсветка в ванной</option>
        <option value="ZWayVDev_zway_30-0-37">Подсветка кухни</option>
        <option value="ZWayVDev_zway_45-0-37">Розетка</option>
        <option value="ZWayVDev_zway_6-0-37">Свет в балке</option>
        <option value="ZWayVDev_zway_8-0-37">Свет в ванной</option>
        <option value="ZWayVDev_zway_2-0-38" selected="selected">Свет в гостиной</option>
        <option value="ZWayVDev_zway1_6-0-37">Свет в детской</option>
        <option value="ZWayVDev_zway_5-0-38">Свет в кабинете</option>
        <option value="ZWayVDev_zway1_3-1-37">Свет в коридоре</option>
        <option value="ZWayVDev_zway_14-0-37">Свет в спальне</option>
        <option value="ZWayVDev_zway_50-0-37">Свет в спальне над кроватью</option>
        <option value="ZWayVDev_zway_12-0-38">Свет в туалете</option>
    </select>`
'

**Comment by vades** [comment]
This output is rendered by Alpaca  and by default the items are sorted alphabetically. Developer can set sorting in the module settings. Something like:
"optionLabels": ["Vanille", "Chocolat", "Café", "Fraise", "Comme"],
        "sort": function(a, b) {
            if (a.text > b.text) {
                return -1;
            } else if (a.text < b.text) {
                return 1;
            }
            return 0;
        }
More info: http://www.alpacajs.org/docs/fields/select.html

**Comment by PoltoS** [comment]
Why sort is incorrect? As you see, from my list, the output is incorrect. Check for example:
<option value="ZWayVDev_zway1_6-0-37">Свет в детской</option>, while 
Свет в детской is ZWayVDev_zway_2-0-38 and not ZWayVDev_zway1_6-0-37

**Comment by ronie-z-wave** [comment]
that is no sort problem ...

thats a problem that effects users with more than one gateway ... I'll to figure out why it isn't in correct order ...

**Comment by ronie-z-wave** [comment]
fixed with:

https://github.com/Z-Wave-Me/home-automation/commit/8abb8c3f09d8017774b43cb0f6489d5e08f511fe
