### ISSUE TITLE
UI does not show correct thermostat scale, min, max values

### ISSUE THREAD

**Issue by silverhack77** [Z-Wave-Me/zwave-smarthome#169]
Z-Way server version 2.2.2
UI version 1.4.0

I have modified /opt/z-way-server/config/Defaults.xml to have:
<SensorMultilevel>
        <Fahrenheit>1</Fahrenheit>
</SensorMultilevel>
<ThermostatSetPoint>
        <Fahrenheit>1</Fahrenheit>
</ThermostatSetPoint>

and restarted the z-way-server  service.
 
The SmartHome UI still shows temperature scale in C, but reports correct device setting (74 deg Fahrenheit) and if I try to change the setting in SmartHome UI, it only allows min 5 through max 40.

![image](https://cloud.githubusercontent.com/assets/19563901/15833591/569b4402-2bdc-11e6-9922-46a8f99b77a7.png)

If I click on the ^  here, it changes 74 to 40 and will not go any higher

![image](https://cloud.githubusercontent.com/assets/19563901/15833616/7ae8cb9a-2bdc-11e6-9fdf-cb26f5d8cee9.png)

**Comment by silverhack77** [comment]
I have to resort to changing the thermostat setting using: 
http://raspberrypi:8083/ZWaveAPI/Run/devices[16].instances[0].commandClasses[67].Set(2,74)
or
http://raspberrypi:8083/ZAutomation/api/v1/devices/ZWayVDev_zway_16-0-67-2/command/exact?level=74

and both of these work correctly.

**Comment by maros** [comment]
IIrc the min/max setting of a thermostat can be changed by setting metrics:min and metrics:max http://raspberrypi:8083/JS/Run/controller.devices.get(%22DeviceId%22).set(%22metrics:max%22,90)

**Comment by PoltoS** [comment]
It looks like engine still remembers old values from old scale. Either delete this device from config.json or re-include it in Z-Wave.

**Comment by silverhack77** [comment]
marcos:
Yes, I can change the min/max metrics using the JS/Run method and now when I use the SmartHome UI I see this:
![image](https://cloud.githubusercontent.com/assets/19563901/15834636/4380c8ba-2be1-11e6-99a2-6d0c67eaf080.png)
So the circle indicator now shows the correct percentage to maximum, but if I click on the ^ to increase, it still gets set back to 40.

PoltoS:
I did not see the individual devices in 
/opt/z-way-server/automation/defaultConfigs/config.json
(attached my config.json)
So I will try to exclude and re-include the device in Z-Wave, and will post the results later tonight.

**Comment by silverhack77** [comment]
config.json

[config.json.txt](https://github.com/Z-Wave-Me/zwave-smarthome/files/301181/config.json.txt)

**Comment by silverhack77** [comment]
A combination of both suggestions was needed.
Here is what I did:
1) remove device
2) re-include the device
3) let interview complete
4) Set device description  (chose the description for my CT30 thermostat)
5) Change min, max, and scaleTitle using the JS API (see below)
6) Re-interview device

Here are the commands I used:
(temperature sensor)
http://raspberrypi:8083/JS/Run/controller.devices.get(%22ZWayVDev_zway_16-0-49-1%22).set(%22metrics:scaleTitle%22,%22%C2%B0F%22)

(heating)
http://raspberrypi:8083/JS/Run/controller.devices.get(%22ZWayVDev_zway_16-0-67-1%22).set(%22metrics:scaleTitle%22,%22%C2%B0F%22)
http://raspberrypi:8083/JS/Run/controller.devices.get(%22ZWayVDev_zway_16-0-67-1%22).set(%22metrics:min%22,50)
http://raspberrypi:8083/JS/Run/controller.devices.get(%22ZWayVDev_zway_16-0-67-1%22).set(%22metrics:max%22,90)

(cooling)
http://raspberrypi:8083/JS/Run/controller.devices.get(%22ZWayVDev_zway_16-0-67-2%22).set(%22metrics:scaleTitle%22,%22%C2%B0F%22)
http://raspberrypi:8083/JS/Run/controller.devices.get(%22ZWayVDev_zway_16-0-67-2%22).set(%22metrics:min%22,50)
http://raspberrypi:8083/JS/Run/controller.devices.get(%22ZWayVDev_zway_16-0-67-2%22).set(%22metrics:max%22,90)

Now in the SmartHome UI it is correct:
![image](https://cloud.githubusercontent.com/assets/19563901/15837149/d337c548-2bec-11e6-9325-4db652dc578e.png)

**Two followup questions:**
A) Should this issue be closed, or be moved to the z-way backend to have these values set correctly after the interview?

B) The Expert UI still shows incorrectly.   Is there a separate github repo that I should open a issue for that?
![image](https://cloud.githubusercontent.com/assets/19563901/15837227/29d0e7a4-2bed-11e6-9e82-c5ee4fc6c235.png)

**Comment by PoltoS** [comment]
That looks strange. Can you exclude and include and show ZAutomation/api/v1/devices/XXX data for the device? And also ZWaveAPI/Run/zway.devices[XXX].ThermostatSetpoint.data

Let's check this. I believe backend should handle this correctly.

As for Expert UI, this is a bug. Thanks for the report. I've fixed it and it will become part of next release: https://github.com/Z-Wave-Me/ExpertUI/commit/a92263e7cd5e507272d4d4c41bdd9a0d0ad8186e

**Comment by silverhack77** [comment]
I have excluded and included the device (it is now device 33).  

Here is the results from /ZAutomation/api/v1/devices
[devices.json.txt](https://github.com/Z-Wave-Me/zwave-smarthome/files/301715/devices.json.txt)

Here is the results from /ZWaveAPI/Run/zway.devices[33]
[zway.devices[33].txt](https://github.com/Z-Wave-Me/zwave-smarthome/files/301717/zway.devices.33.txt)

It is still working correctly in the SmartHome UI, and I will follow/update https://github.com/Z-Wave-Me/ExpertUI/commit/a92263e7cd5e507272d4d4c41bdd9a0d0ad8186e for the Expert UI.

**Comment by PoltoS** [comment]
So we can close it?

**Comment by silverhack77** [comment]
Yes, I think so.   Thanks for the help!
