### ISSUE TITLE
Logical Rules. Cant set Dimmer 0

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#17]
In module Logical Rules cant set Dimmer  = 0, only 1-99

**Comment by Quax1507** [comment]
Any progress on this issue?

**Comment by PoltoS** [comment]
@vades 

Please merge these changes into our alpaca used in the project 
https://github.com/PoltoS/alpaca/commit/9f5da13393885b8615a975bc3295a7f34ac0361d
https://github.com/PoltoS/alpaca/commit/dbb61ddd03aebdaf2b882e21efbff09db59c5640
https://github.com/PoltoS/alpaca/commit/a1ba2ec7c0ea1f140a5d2adeb10fa5b37b2c437d
