### ISSUE TITLE
Version v2.2.3-rc3: Lost icons on virtual devices

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#174]
Just upgraded test rig to v2.2.3-rc2. Seems I lost the icon of my App **Arithmetic** as shown in image below. Similar on my modules XML device, and PVLogger. Not on Wunderground, and SolQoS where an icon based on a value is written to the vDev. Seems that the default App icon is no longer applied.

![capture](https://cloud.githubusercontent.com/assets/7747627/16539472/b3280c42-4044-11e6-87dd-ca8ab5250413.PNG)

note: I think my modules comply with the specification in http://developer.z-wave.me/?uri=help

**Comment by pz1** [comment]
My mistake; this icon apparantly replaces the previously used icon that displays a lowercase i.
Is there a way to assign a custom icon? I remember I have seen something about that but could not find it again.

**Comment by maros** [comment]
Just set metrics:icon. Icon can be either an absolute url (starting with http:// or https://), identifier (only those supported by the UI) or a relative uri. If you want to serve images from your modules htdocs directory use "/ZAutomation/api/v1/load/modulemedia/ModuleName/icon.png"

**Comment by pz1** [comment]
Thanks Maros. I was aware of the solutions you provide. I thought there was some discussion about icons that could be added easily by "untrained" users. Where appropriate I'll fix my modules to display something meaningful instead of this awkward image.
