### ISSUE TITLE
SmartHome UI ERROR: Unable to load license key from remote server

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#177]
This error occurs when I click **Management** in the tools menu. Also at the moment I save a newly added room to user anonymous, this error pops up. The actions I did seem to have completed properly though.

_Note:_ On the offending machine I have imported devices from a second Zway installation. Those devices also do work fine though. None of the remote devices were involved in my actions as far as I could see.

![licencekeyerror](https://cloud.githubusercontent.com/assets/7747627/16899886/59a962a8-4c13-11e6-8fa7-8ea818cca637.PNG)
_update 20161022: Stil problem in v2.2.4_

**Comment by mtruijen** [comment]
Same error here...

A year ago I reported issue #253. This was with a brand new installation (OS and z-wave-me software).
Now again with a brand new installation (OS and z-wave-me 2.2.3) also don't get beyond the installation when I get the SmartHome UI - ERROR.

**Comment by mtruijen** [comment]
I got this resolved by using Firefox.

**Comment by pz1** [comment]
> I got this resolved by using Firefox.

I am using Firefox (always try to stay at latest version 49.0.1 now). The error still occors here on my Rpi2/UZB with v224-rc16, which imports devices from RaspiB/RaZberry wit v224-rc17.

**Comment by PoltoS** [comment]
The problem will be solved once we finish to move our servers to a new platform.

**Comment by juliank** [comment]
@PoltoS: This is still a problem with v2.3.5 when using Chrome (v60.0.3112.113).

I get the "Unable to load a license key from the remote server." when entering the Management page. And in the developer console I can see these two errors:

Failed to load resource: net::ERR_INSECURE_RESPONSE hrix.net/shuiapi/licence/?uuid=f2918e9cfc2ede7e6c94a47b8154f0ac
---------- ERROR: ---------- Object>(anonymous) @ build.js:sourcemap:7574

And also the Time Zone option is missing as well from the Management page.

In Edge everything appears to be working.

**Comment by PoltoS** [comment]
You need to clear cache in the Chrome after upgrade
