### ISSUE TITLE
Online App store :  "Last updated"-ordering seems not correct

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#178]
Not a serious problem, but worth mentioning I think: If I select ordering type "*Last update*" I would expect to see the most recent first. However, if I look at the screen for example App **Multi Button** (2016-07-07) is further down than **Timer Switch** (2016-06-23).

Also I fail to see the difference between "*Last update*" and "*Newest*"

**Comment by vades** [comment]
The difference between "Last update" and "Newest"
Last update: the time of  latest update in the DB. App is already stored and activated in the Store. Author can update an app with new version etc.
Newest: an App is newly uploaded to the Store
