### ISSUE TITLE
strange sting on widget

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#180]
Look on the "260 undefined" on the widget. And after disabling 24 Hours History it do not disappear.

![2016-08-12 14 52 52](https://cloud.githubusercontent.com/assets/3664383/17626659/d1c5f4d8-60b6-11e6-959b-2fe9450dafab.jpg)

**Comment by vades** [comment]
The value "260 undifined" is from "updateTime". What I can do is to check if updateTime is a valid time. If not show nothing.
