### ISSUE TITLE
Lost App "Sensor Values Logging" in Active Apps

### ISSUE THREAD

**Issue by Toffi32** [Z-Wave-Me/zwave-smarthome#181]
I use Z-way (2.3.3) -> correct v2.2.3 !! / UI Version 1.4.3

I installed "Sensor Values Logging" and make the inputs and saved it.
The App is not shown in the "Active" Apps but it is active - data is transferred to the website I mentioned in the form of the app.

I tested it with other sensor data. Same result. No entry in the Active apps, but data is transferred.
so unfortunately I am not able to kill or modify these apps.

What can I do?

**Comment by Toffi32** [comment]
Of course it is  Firmware v2.2.3 !!!

**Comment by PoltoS** [comment]
Please open browser console and see for errors when you navigate to the Active Apps page.

**Comment by Toffi32** [comment]
Thanks for your response.
I am not familiar with the console so ...

this is what I get (for chrome):
Updating from server response: device ID: SummarySensor_19, metrics.level: 22.9, updateTime: 1471164271, iconPath: storage/img/icons/temperature.png
build.js:15650 Updating from server response: device ID: ZWayVDev_zway_4-0-49-1, metrics.level: 22.9, updateTime: 1471164269, iconPath: storage/img/icons/temperature.png
build.js:15650 Updating from server response: device ID: ZWayVDev_zway_4-0-48-1, metrics.level: off, updateTime: 1471164306, iconPath: storage/img/icons/motion-off.png
build.js:15650 Updating from server response: device ID: ZWayVDev_zway_4-0-48-1, metrics.level: off, updateTime: 1471164307, iconPath: storage/img/icons/motion-off.png

I don´t see any errors.
Same with firefox (which is only german ...)

**Comment by PoltoS** [comment]
@vades any idea?

**Comment by Toffi32** [comment]
Hello!
Thanks again for dealing with this issue.
I made a factory reset and included only one sensor and set up the sensor logging app.
Same again. No Sensor logging app in the active apps section, but the app is active/working, as values are submitted to the loggig website.

**Comment by vades** [comment]
This "Updating from server response: ..." is for debug purposes only (should be commented). We can't recognize a bug without error log.
What happens if "you save it"? Is an alert window shown?

**Comment by Toffi32** [comment]
As I said, I am not familiar with the console and so an. This is what I get, when I hit F12 in Firefox and go to "Konsole" (german).
I just created anonther "Sensor logging" app, which is also working instantly but not shown in active apps ...
There is no alert window. Only this little "Logging ..." window. Than back to the "online app" section.

**Comment by Toffi32** [comment]
![z-wave_active apps](https://cloud.githubusercontent.com/assets/21006155/17658370/9815e31c-62cb-11e6-96b7-dab45a49e9ae.jpg)
I played a little bit wit the firefox tools.
See the screenshot attached. May be it helps.

It looks (for me) like there is no "Instance" für die "Sensor logging App", which I created (2 of them) before the two in the screenshot.

**Comment by vades** [comment]
Sorry but from this i can't catch an error. Do you have something about "Sensor Values ..." in your event log (section events)?
![events](https://cloud.githubusercontent.com/assets/1451741/17659486/229c1824-62d3-11e6-9a78-65c66b2089ee.png)

**Comment by Toffi32** [comment]
No, there is nothing in the event log. See attachment.

I have a Popp Hub. I had a look at the source file of config.js (1.4.1), which is downloadable at gihhub.
I have noticed, that there are _hidden_apps_. For the default config **hidden_apps** is without '...' for the other popp, wd, ... it is in '' ('hidden_apps').
I dont know if this means something ....
![zwischenablage02](https://cloud.githubusercontent.com/assets/21006155/17661704/1718e492-62e1-11e6-8101-c17e6a67eabd.jpg)


I tried also to install the app "Load custom JavaScript code", as it is also in "hidden_apps". I saved it (without any code) without alert message. It is also not visible in active Apps.

![z-wave_active apps](https://cloud.githubusercontent.com/assets/21006155/17661628/9c6f8f52-62e0-11e6-8e70-ede12dfb9c79.jpg)

**Comment by Toffi32** [comment]
I did some trial and error research ...

When I activate "Expert View - Show System Apps" in "My Settings" I see finally the "Sensor Values Logging" App!!!
Sadly this isn´t mentioned anywhere ...
It would be better to have them present in the "Active Apps" Section also in "Normal View"
