### ISSUE TITLE
Aeotec Siren Gen5 

### ISSUE THREAD

**Issue by michapr** [Z-Wave-Me/zwave-smarthome#182]
Is there any chance to add this funtion for switching sound and volume at Siren Gen5?
So user could use same siren for door ring and alarm signal (as sample)

Aeotec told me that siren could be reconfigured for such a usage.

First Signal Received
{
    Configure Siren Gen5 (param 37 [2 byte hex] = 0x103) //set sound #1 at volume 3
    Delay 100              //siren may need a short delay time to configure properly before turning ON
    Turn Siren Gen5 ON
}

Second Signal Received
{
    Configure Siren Gen5 (Param 37 [2 byte hex] = 0x201) //set sound #2 at volume 1
    Delay 100
    Turn Siren Gen5 ON
}

**Comment by PoltoS** [comment]
This can be done using a custom module. One need to write a module for this. Not sure we can schedule this in our priority list, but looks a perfect candidate for community contribution.

I would do a configuration like this:
`config = {vDev: <vDevId>, buttons: [{ringTone: <ringToneNo>, volume: <volumeLevel>}]}`

This will generate N (size of buttons array) toggleButtons to play corresponding ringtones.

**Comment by michapr** [comment]
Good idea - but I do not have such a siren here, it was a user request.

Maybe somebody else who own this device can do it.
