### ISSUE TITLE
infinite loop on login

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#184]
![inf](https://cloud.githubusercontent.com/assets/3664383/17810167/2ea85a3e-6624-11e6-8314-cbdf072789dd.png)

**Comment by PoltoS** [comment]
Happens on server restart (I refresh SH UI). I've "keep me logged on" checked. This started after checking this.

**Comment by vades** [comment]
I can not catch this issue but I've added the function which delete remeber me cookie if response status is 401. This avoid to redirect to app if user is unauthorized.

**Comment by PoltoS** [comment]
Will test in next rc
