### ISSUE TITLE
Filter function in elements prevents further use of UI elements

### ISSUE THREAD

**Issue by christianpaetz** [Z-Wave-Me/zwave-smarthome#185]
Assuming I have one  - lets say - thermostat in the system and filter in elements view than I see only the thermostat. The filter is kept even if I leave to a different page. Now I exclude this Thermostat. The filter on elements view is still active but I cant remove the filter anymore since the filter header is not shown.

**Comment by vades** [comment]
Fixed

**Comment by zwave-mke** [comment]
closed
