### ISSUE TITLE
Periodic Switch polling turns device off

### ISSUE THREAD

**Issue by i8beef** [Z-Wave-Me/zwave-smarthome#186]
I installed Periodic Switch Polling and am seeing an issue. It appears that when it polls the target devices after a remote change, that it resets the device back to whatever value it was set at the last time it polled it. IE, if it was off, and someone hits the switch to turn it on, the next minute when it polls it, the dimmer gets turned back off.

Similarly, if the light was on during the last poll, and its turned off physically, the next poll will make it turn back on.

Note, that if the change is made physically and then the update triggered by the expert UI, this does not happen.

**Comment by PoltoS** [comment]
It should be fixed by https://github.com/Z-Wave-Me/home-automation/commit/ba97f5e88c1ed9570eabf1a372a19e040b68700e

Next release will implement it. You can also add this fix manually.

Please confirm to let us check the issue

**Comment by i8beef** [comment]
Does indeed seem to fix the issue so far. Seems you guys have a lot of fixes that are rolled in right now but not released... getting close to a release date?

**Comment by zeair** [comment]
Hey i8beef, how did you managed to install Switch Polling - I can see only Sensor, Meter and Door apps...

**Comment by i8beef** [comment]
It's called "Periodic Switch Polling". Make sure you don't have "featured apps" selected in the filter, change it to "All apps". That trips everyone up and I hope they change that in the future, or make it more obvious.
