### ISSUE TITLE
Upgrade to v2.2.4-rc17 leads to erroneous? error messages

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#188]
*Smarthome* - In my own module Wunderground, which is a slightly modified version of the standard distribution's **OpenWeather App**, I do get *since the upgrade to rc17*, repeated messages "Can not parse weather information". In the log file I see "*Notification: error (module): Can not parse weather information*". Apparently the module name is not found, but is definitely specified in index.js. Besides if I interrogate the device, the full set of metrics can be read and seen in the UI. I vaguely remember to have seen this in a much older version too.
I am puzzled.

**Comment by ronie-z-wave** [comment]
Hi,

we've checked your app on 3 RPi's (2x RPi B+ & 1x RPi 2 - all with v2.2.4-rc17). Usually it seems to work and it has failed only once. Think maybe the side has blocked the request or answer because the request delay was to low. This behaviour we could see on e.g. OpenWeather api ...

Btw. why do you want to use **deviceType: 'text'** for wind direction device? Maybe **sensorMultilevel** is a better choice ;) 

Otherwise the correct level should be shown in element by using **metrics.text**  instead of **metrics.level**

cheers

**Comment by pz1** [comment]
> Btw. why do you want to use deviceType: 'text' for wind direction device? Maybe sensorMultilevel is a better choice ;) 

- I should have checked the deviceType in the apiari document. (Apparantly [this unfinished discussion](http://forum.z-wave.me/viewtopic.php?t=21446&p=57076#p57022) still hung around in my brain)
- My understanding of sensorMultilevel was that it is a continuous signal of *type*:**numerical**. My wind direction device has 16 predefined discrete states, similar to the modes in heating. Those have up to [three character designators](http://climate.umn.edu/snow_fence/components/winddirectionanddegreeswithouttable3.htm).

> Otherwise the correct level should be shown in element by using metrics.text instead of metrics.level

- I did choose metrics:level because I thought that would force the value of wind direction to be shown in the UI

Thanks, Pieter

**Comment by pz1** [comment]
Apart from this problem with App Wunderground I had at the same time a problem with App PVLogger. The point was, that after initialisation of the module, the metric:level of one of its vDevs was no longer being updated. 
After days of trial and error that issue was miraculously fixed when I added a metric:level2 that got the same value. The problem did not occur again after removing metric:level2. Around that time the Wunderground problems stopped as well. 
I am confused on what cause/effect has been happening here. Have no hope to find a clue. So since things are working fine again, I close this issue.
Thanks for the suggestions!
