### ISSUE TITLE
Deactivated sub-sensor (e.g. temperature) of a fibaro flood sensor can't be enabled back again - disappears.

### ISSUE THREAD

**Issue by klaasjoerg** [Z-Wave-Me/zwave-smarthome#191]
Once subdevices e.g. fibaro watersensor has been manually deactivated (e.g. temperature sensor) it's not possible re-activating it easily again.  It's not even shown anymore in the smart-UI.

Only by doing a complete exclude and re-include I was able to get access to all 3 sensors again. That is basically independent of the device type. So regardless of it's a watersensor or a switch with meter etc. | Version number: v2.2.3 | SmarHome UI version: 1.5.0

**Comment by klaasjoerg** [comment]
Ok, Don't know if it's a issue with the UI or with the automator.
However, once an instance has been permanently_hidden, I didn't found a way to re-activate/unhide that again.
At the end I simply ended up manually edit the file "/opt/z-way-server/automation/storage/configjson-....." and replaced ""permanently_hidden": true," into "false" and it's fine again.

**Comment by pz1** [comment]
> At the end I simply ended up manually edit the file "/opt/z-way-server/automation/storage/configjson-....." and replaced ""permanently_hidden": true," into "false" and it's fine again.

That's how I ended up doing it.  It would be nice if the could be *re-activated* in the smarthome UI:
![deactivate](https://cloud.githubusercontent.com/assets/7747627/19417836/00c1f04c-93b7-11e6-882b-e134b9777a79.PNG)

**Comment by ronie-z-wave** [comment]
Changed descriptions of this widget configurations to make it (hopefully) more understandable -> 05a927b3981bf4aa36efde87ae999ec70139d31d

As pz1 has already mentioned it is possible to reactivate the widget via Menu > Devices > Management > Z-Wave Devices > Device #ID.  If you don't want to deactivate it completly use 'Hide element' instead to make it invisible. Use 'Show hidden' filter to make them visible again.

**Comment by klaasjoerg** [comment]
Ok, but just to be sure one more question:
"Hiding" meant for me really just "hiding" in the UI
But for example, if I am using homebridge-zway the devices would still be there, because it's just "UI-hidden", correct?

In this specific case I choosed to "deactivate" (and not only hide) because it wasn't a matter of optical but more technicallly - simply didn't want to show certain sensors on IOS/Siri/Homekit. 

However, regardless of that: 
If I am "deactivating" something (instead of hiding) it should also be possible to re-activate it again, right?

**Comment by pz1** [comment]
> As pz1 has already mentioned it is possible to reactivate the widget via Menu > Devices > Management > Z-Wave Devices > Device #ID

That is not what I intended to say. Just the opposite. I would like to have that option! (But may be it is there already, but just as in an other recent post of mine, it is not visisble for some reason)

**Comment by klaasjoerg** [comment]
Correct. I just re-checked  what @ronie-z-wave  mentioned/cited:
I definetively can not see de-activated devices to be able to re-activate them again. They are not shown at all anymore. Nowhere.

**Comment by ronie-z-wave** [comment]
ok, my misstake ... it should be there but it isn't. We'll change it :)

**Comment by vades** [comment]
Fixed
