### ISSUE TITLE
Preselection of the app category "Featured apps" in the views: Local Apps and Online Apps

### ISSUE THREAD

**Issue by pathec** [Z-Wave-Me/zwave-smarthome#193]
I had several times the case that new users did not find my app, because the preselection was set. 
Maybe it's better to show all apps by default or at least a button at the end _Show more_ if a restriction has been set.

**Comment by vades** [comment]
Done
![show-more-apps](https://cloud.githubusercontent.com/assets/1451741/19590043/0ecd12ea-9770-11e6-946b-cdc05ca9b6c6.png)

**Comment by pathec** [comment]
Perfect. Thanks a lot!

**Comment by aivs** [comment]
Not perfect, what is the reason to hide apps?

**Comment by aivs** [comment]
If you want to show apps in categories, show categories!
Users do not understand how to see the categories and when they find categories, then use only "All"

**Comment by vades** [comment]
The reason is "Project requirement":
Firstly to display preselected "featured apps" and then to display other apps.

**Comment by aivs** [comment]
24 Device History, If-Then, Local Weather and Schedule, It's really featured apps?
Only the user knows which apps are features for him, after some times of using. So "featured apps" should be filled with time. 
I believe that we need to display all categories, and not to hide them inside the button.

**Comment by vades** [comment]
The featured apps is a list in the featured_apps (config.js)
