### ISSUE TITLE
Question : is data recorded in z-wave-me ?

### ISSUE THREAD

**Issue by VD17593** [Z-Wave-Me/zwave-smarthome#194]
I'm thinking about providing a consumption chart for energy meters. 
I was wondering if data is already recorded somewhere in z-wave (I am starting to discover this project).
Or what could be the easiest way to record data, maybe with some kind of cron?

**Comment by pz1** [comment]
See in the [App store](http://developer.z-wave.me/?uri=public#/web/apps). Is also accesible from the SmartHome UI if you want to download/install any of these

**Comment by VD17593** [comment]
Thanks for this answer. I saw there are a lot of apps available : it will take me some time to search for the right combination.
But I'm wondering : what is the purpose of these Apps? That an individual user picks what interests him? Or is the purpose to make a nice combination of them and propose this as a solution to the public?

**Comment by pz1** [comment]
Afaik it is intended as a community thing. Apart from the ZWay developers, some users have contributed as well. 
There are apps that provide extensive weather information, some correct devices that are not strict Z-Wave, some do logical functions. You can see it as a lego box, but there are more complex apps e.g. to govern the ventilation of a whole building. The built-in _Schedule_ app can do cron like things.
For example you use the a storm warning from the weather app in a IfThen app, to raise your sunscreens.

See also [recipes on the forum](http://forum.z-wave.me/viewforum.php?f=3424), where some apps are discussed. (Unfortunately as with most forums, not everything is up to date)

**Comment by VD17593** [comment]
Indeed the Schedule app could be useful.
I also saw that there is a 'SensorsPollingLogging' app. I'll have a look at that one.

However I saw this one is a 'hidden' one. Any quick tips on how to un-hide it?

(I tried to send you an private message through the forum, but since I just joined the use is limited)
