### ISSUE TITLE
Update time in UI is wrong

### ISSUE THREAD

**Issue by dolpheen** [Z-Wave-Me/zwave-smarthome#195]
In UI update values show differnet time that in Expert interface.
The snapshots taken at 26.10.2016.
rc-2.2.4
![screenshot-192 168 10 41 8083 2016-10-26 11-01-21](https://cloud.githubusercontent.com/assets/5053583/19718038/3df9241e-9b6c-11e6-8ccf-1a6c75a70444.png)
![screenshot-192 168 10 41 8083 2016-10-26 11-04-52](https://cloud.githubusercontent.com/assets/5053583/19718039/401ec9ba-9b6c-11e6-90b4-8f759b18a64d.png)

**Comment by PoltoS** [comment]
@dolpheen Have you tested it on 2.2.5?
