### ISSUE TITLE
Need to be able to return the hidden widgets

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#2]
When I choose "Permanently hide this element" in widget settings, the widget disappears. But there is no way to return the widget return
![2015-05-28 14 29 02](https://cloud.githubusercontent.com/assets/2894860/7859040/f211d838-0545-11e5-8089-6c3a375f92c7.png)

**Comment by ronie-z-wave** [comment]
Its already on our TODO list.
