### ISSUE TITLE
Send http POST with body returns an error

### ISSUE THREAD

**Issue by VD17593** [Z-Wave-Me/zwave-smarthome#200]
I'm trying to write a module where I need to send a http request using POST with a body content.
Something like in the modules Notification or SecurityMode.

I manage to send a GET request.
But when I send a POST request I always have an error return.
I tried to include data to the POST different ways.

Is there anyone who knows where could be the problem?

My POST looks like this : 

    http.request({
        url: 'http://www ...',
        method: 'POST',
        async: true,
        auth: 'SomeAuthorization',
        body: 'Some text',
        success: function(response) {
                console.log('success');
        },
        error: function(response) {
                console.log('error');
        } 
    });

**Comment by PoltoS** [comment]
Can you provide an example based on some public services (so you can share the url and auth data if present). We will check it

**Comment by pathec** [comment]
Did you try _data_ instead of _body_?

**Comment by VD17593** [comment]
Hi,

This is an example of a GET with success return : 
(I included temporary credentials for testing purposes)

				http.request({
					url: "https://www.intchart.com/api/pX9Qaq9N/files/Dev1",
					method: 'GET',
					async: true,
					auth: 'Bearer 9ARuFWTkz8fJq5viScL5gnpGh591RvU864CgYTpi',
					success: function(response) {
							console.log('success');
							console.logJS(response);
					},
					error: function(response) {
							console.log('error');
							console.logJS(response);
					} 
				});

This is an example of the POST with error return:
(I tried with body or data included : same result)

				http.request({
					url: "https://www.intchart.com/api/pX9Qaq9N/files/Dev1/names",
					method: 'POST',
					async: true,
					auth: 'Bearer 9ARuFWTkz8fJq5viScL5gnpGh591RvU864CgYTpi',
					body: '1|2|3',
					//data: '1|2|3',
					success: function(response) {
							console.log('success');
							console.logJS(response);
					},
					error: function(response) {
							console.log('error');
							console.logJS(response);
					} 
				}); 

I tried this POST request with an other application and the api works fine. 

So it is probable that an error occurs when the http is sent. When you look at the response data for the POST, it is as if the 'auth' is removed when the http is sent : 

> There is an error with your request : you entered a wrong URL or you have to include an AUTHORIZATION header.

**Comment by pathec** [comment]
Please try this:

```
http.request({
	...
	async: true,
	headers: {
		'Authorization': 'Bearer eyJhbGciOiJIUzI1NiJ9....'
	},
	...
});
```

**Comment by VD17593** [comment]
Super ! This is it.

I included headers the way you said, added also a Content-Type in the header, and used data (and not body), and I get a success return.

Thanks a lot @pathec
