### ISSUE TITLE
Big padding for widgets in mobile view

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#201]
Are you agree that in the mobile view does not need a big padding for widgets?
<img width="851" alt="2016-11-09 13 09 35" src="https://cloud.githubusercontent.com/assets/2894860/20135338/5276b78e-a680-11e6-9883-e22cd7457d96.png">

**Comment by zwave-mke** [comment]
hi, agree will schedule this small fix.

**Comment by mh-zwave** [comment]
We change to grid view in mobile view with 3 widget i a row. 
![image](https://user-images.githubusercontent.com/20574625/48406053-d2c0d000-e733-11e8-8fc4-b8a100b7a5f9.png)
