### ISSUE TITLE
No icon for Code device

### ISSUE THREAD

**Issue by VD17593** [Z-Wave-Me/zwave-smarthome#203]
On my installation the icon for the module Code Device is not shown.

Instead sometimes I get the placeholder.png, sometimes just the 'img' tag.

**Comment by pz1** [comment]
Similar questions has been asked before e.g. [in the context of home automation](https://github.com/Z-Wave-Me/home-automation/issues/364). 

I have seen several attempts on github, but none of that work has been available for public testing

**Comment by VD17593** [comment]
Ok. Just communicated in case no had noticed this.
