### ISSUE TITLE
Changes To ZWaveMe API get Error of Handling Data

### ISSUE THREAD

**Issue by Wikibear** [Z-Wave-Me/zwave-smarthome#204]
Z Wave me do some Changes in API. New Devices gets longer ID's. Pimatic can't handle it. Some of my new devices get:

ZWayVDev_zway_8-0-113-7-8-A

ZWayVDev_zway_7-0-67-1

Normally we get only 3 digits. Happens with firmware 2.2.5.

Thanks.

Error: error [pimatic-z-way]: error updating sensor value  Cannot read property 'data' of undefined

**Comment by PoltoS** [comment]
That's not really correct. Those IDs are from the beginning of Alarm devices support.

The naming is simple: 
ZWayVDev - vDev comes from Z-Wave Binding App
zway - name of z-way object. See name in Z-Wave Binding App
8 - nodeId
0 - instance
113 - Alarm CC
7 - type
8 - event
A - Alarm (there were a long time ago second widget on the same event to clear the event)

In the same way
7 - nodeId
0 - instance
67 - ThermostatSetPoint CC
1 - mode (Heat)

**Comment by Wikibear** [comment]
Get an error:
2016-12-01 21:18:25
error [pimatic-z-way]: error updating sensor value for power Cannot read property 'data' of undefined

**Comment by PoltoS** [comment]
when and where does it happern?

**Comment by Wikibear** [comment]
I get a new Thermostate and a new Fibaro Multi Sensor. In zwave me this devices works fine. Thereafter I create a new device and get immediately this error after. 

I have another three or four devices and this are all works fine.

**Comment by Wikibear** [comment]
Please close this issue... I'm totally wrong here. Sorry for that mistake.
