### ISSUE TITLE
Bug in setExactCmd function

### ISSUE THREAD

**Issue by ideasupport** [Z-Wave-Me/zwave-smarthome#207]
For **thermostats** 'metrics:level' is a float quantity, not int, so

`var val = parseInt(v.metrics.level);`

should be

`var val = parseFloat(v.metrics.level);`

in app/controllers/element.js:setExactCmd function

Due to this, val is rounded and "+" and "-" buttons are not working as expected

**Comment by mh-zwave** [comment]
fixed in 30f08c34566d009252e9eb2b10b74ce2726a72fd
