### ISSUE TITLE
Cannot access devices via API

### ISSUE THREAD

**Issue by Quax1507** [Z-Wave-Me/zwave-smarthome#21]
Trying to access a dummy device using api call like

https://ip-of-zway:8083/ZAutomation/api/v1/devices/DummyDevice_95

returns

{"data":null,"code":404,"message":"404 Not Found","error":"Device DummyDevice_95 doesn't exist"}

Problem is in rc43 and rc44, perhaps even before

**Comment by pz1** [comment]
The error does not occur if http instead of https is used [see forum] (http://forum.z-wave.me/viewtopic.php?f=3419&t=21749&p=56986#p56986)

**Comment by Quax1507** [comment]
You are right, pz1
