### ISSUE TITLE
z-wave.me is DOWN

### ISSUE THREAD

**Issue by brainfucker** [Z-Wave-Me/zwave-smarthome#211]
Please upload drivers somewhere else, since your site is constantly down

**Comment by PoltoS** [comment]
It was on maintainance. It is available again

**Comment by pathec** [comment]
Hi @PoltoS.

The _find.z-wave.me_ service was currently not available. After the login appeared the message "502 Bad Gateway". But now it's over again. Perhaps you can look in the logfile, whether it was a critical problem?

**Comment by PoltoS** [comment]
thanks for your message
