### ISSUE TITLE
Asking for how to translate/compyle

### ISSUE THREAD

**Issue by ivnc** [Z-Wave-Me/zwave-smarthome#216]
Hello.

From @raspberrypi-accesible/zwave-accessibility we are trying both to translate and to improve the interface's accessibility, but we are problems with the translation… We located the json of the translations, but we couldn't find any way to see it on the interface, although we included the language as supported in config.js. I found a document which explains how to translate from a working installation, but some of ours don't have any device where trying, and we would like to make a pull request when the translation was finished. We are discussing if this interface is included as a submodule of another z-wave-me github repo, but we didn't locate it. So how can we translate the project to include then it officially through a pull request? We didn't find enoug documentation.

Thanks in advance.

**Comment by PoltoS** [comment]
Please do pull request with your changes. We will accept it and check that your changes are visible in the UI. Thanks!
