### ISSUE TITLE
General image on https://service.z-wave.me/cloudbackup/ in MS paint style

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#218]
I think we need image with more smooth border
<img width="1280" alt="2017-02-09 14 48 00" src="https://cloud.githubusercontent.com/assets/2894860/22782202/0c518276-eed7-11e6-9f01-688d99d143aa.png">

**Comment by ronie-z-wave** [comment]
Think a regular text is more important at the moment -.-

**Comment by zwave-mke** [comment]
done
