### ISSUE TITLE
DoorLock Status

### ISSUE THREAD

**Issue by ripper121** [Z-Wave-Me/zwave-smarthome#222]
The DoorLock Status is not Displayed.
I cant see if the Door is Close or Open.

**Comment by ToddGreenfield** [comment]
@ripper121 Upgrade to 2.3.1 with UI 1.7.0. I just did that now and it seemed to fix this problem for me, but now I have a different problem in that if I use Smarthome UI to open my lock, when the auto-lock feature kicks in and locks, Smarthome UI doesnt get the update. The same happens for manual lock operation. Also, the lock seems to have disappeared from the expert UI under Control-Locks so I cant see status there.

https://github.com/Z-Wave-Me/home-automation/issues/426
