### ISSUE TITLE
 Time zone and access from home network not saving some selections properly

### ISSUE THREAD

**Issue by austinmroczek** [Z-Wave-Me/zwave-smarthome#228]
I enabled the "Time zone and access from home network" app and select America/Los Angeles timezone and hit save.  If I re-open the app, it shows America/Whitehorse selected.

UI	1.7.0-RC-9

**Comment by ronie-z-wave** [comment]
Hi austinmroczek,

that's a known issue but usually has no bad effect on TZ setting. It is related to duplicated TZ id's within select box. So your configured TZ for 'America/Los Angeles' should be the same as 'America/Whitehorse' but UI uses the last entry with same ID ...

We'll fix this in one of the next releases.
