### ISSUE TITLE
v2.0.1 release: The tools menu lacks a link to the Expert UI

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#23]
Under the tools icon at the upper right side of the UI there should be a link for administrators to the Expert UI, which opens in a new browser tab. Present situation is awkward if one is developing a system

**Comment by PoltoS** [comment]
Agree, vote for this, but we have internal debates about it.

Niels, may be in [Gear]->Devices tab at least?

**Comment by pz1** [comment]
Under *Devices/Zwave* would make sense to me if you foresee similar Expert UI for EnOcean.
