### ISSUE TITLE
Logout from Smart Home UI

### ISSUE THREAD

**Issue by christianpaetz** [Z-Wave-Me/zwave-smarthome#230]
Please change the logout button in SHUI.

If 
(url contains find.zwave.me) 
then 
redirect to find.zwave.me/zboxweb
else
do as usual and destroy local cookie

**Comment by PoltoS** [comment]
If
(url contains **find.z-wave.me** or **findcit....**)
then
**destroy the cookie**
redirect to **<domain from above>**/zboxweb
else
do as usual and destroy local cookie

**Comment by vades** [comment]
Added new key "logout_redirect" into config.js:

'logout_redirect':
{ 'find.z-wave.me': 'https://find.zwave.me/zboxweb' }

After logout app check if host is in the  logout_redirect list. If yes redirect to given url otherwise redirect to SHUI login page

**Comment by vades** [comment]
Done

**Comment by zwave-mke** [comment]
closed

**Comment by PoltoS** [comment]
Please always use find.z-wave.me and Mott find.zwave.me. check other places too. Those are different domains and cookies might remain valid in one site and destroyed on another
