### ISSUE TITLE
Disk space monitor (feature Request)

### ISSUE THREAD

**Issue by ripper121** [Z-Wave-Me/zwave-smarthome#231]
Can you add an Option to display the use of Disk Space and if Disk Space gets to low show a warning.
When the warning appears the the User will be ask if they want to delete Logs and History's and old Z-Way releases.

On razberry hub version space should be no problem, but with the Popp Hub 2 we have only 4 GB and if they full there is no Access possible, even not via SSH. Then the user needs to send it back to popp

**Comment by karei90** [comment]
Should be no problem to write an app for that case, feel free to do so ;)
