### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#233]
The error appears when push "Save" in My Settings-->Language menu.
PUT http://192.168.0.23:8083/ZAutomation/api/v1/profiles/1 500 (Internal Server Error)
<img width="1280" alt="2017-06-16 12 30 29" src="https://user-images.githubusercontent.com/2894860/27221109-1d42a002-5290-11e7-9fde-3baaad19ba04.png">

**Comment by ronie-z-wave** [comment]
Seems to work now with latest UI from dev.
@aivs please check.

**Comment by aivs** [comment]
Ok on 1.7.0
