### ISSUE TITLE
Broken section Devices-->Add new

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#234]
This section is broken for more than a year. 
<img width="1280" alt="2017-06-16 12 36 10" src="https://user-images.githubusercontent.com/2894860/27221264-a37fc0e6-5290-11e7-8253-42a093b09e1a.png">

**Comment by ronie-z-wave** [comment]
Nope, seems to work (admin/user role).
fyi this view is frequency dependend since a year.
Please change the controller frequency and you'll recognize that the vendors will change ;)

@aivs please check.

**Comment by PoltoS** [comment]
We need to fix this somehow since on frequencies like RU, IN, CN,... have almost no certified devuc s in the DB but have a lot of devices on the market. How to change this? Duplicate records in P1 DB? Or make some provisioning lists that overrides info from the DB

**Comment by ronie-z-wave** [comment]
We've now changed the view so that EU vendors are shown always + additionally the vendors of currently frequency.
So in in your case it will be  EU and RU (check last build)

Usually the correct way should be to update the vendor DB entries in our manual DB ... seems that there are almost no entries for RU and some other frequencies ;)

**Comment by aivs** [comment]
Now list shows
<img width="1280" alt="2017-07-31 17 48 50" src="https://user-images.githubusercontent.com/2894860/28783277-8af6cb18-7618-11e7-90eb-d2c2a50d5acc.png">

But the section is empty
<img width="1280" alt="2017-07-31 17 50 47" src="https://user-images.githubusercontent.com/2894860/28783426-00735bc2-7619-11e7-9d0a-46b552dfd2ba.png">

**Comment by ronie-z-wave** [comment]
have you already tried Z-Wave device database update?

there should be a hint to force this if request get's 404 ...
