### ISSUE TITLE
Can't rename widget

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#235]
The error appears when push "Save" in widget settings
PUT http://192.168.0.23:8083/ZAutomation/api/v1/profiles/1 500 (Internal Server Error)
<img width="1280" alt="2017-06-16 12 40 06" src="https://user-images.githubusercontent.com/2894860/27221390-1981607e-5291-11e7-81d4-b49246a33b10.png">

**Comment by ronie-z-wave** [comment]
Seems to work now with latest UI from dev (admin role).
@aivs please check.

**Comment by aivs** [comment]
done
