### ISSUE TITLE
Some icons missing

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#238]
Icons missing for value "metrics:icon":
seismic
acceleration_x
acceleration_y
acceleration_z
co
cooling
flood

For all these "metrics:icon" icon is empty
<img width="397" alt="2017-06-21 16 30 43" src="https://user-images.githubusercontent.com/2894860/27386640-23e1b552-569f-11e7-83c8-8cc384a5c937.png">

smoke, alarm, tamper has same icon - switch
<img width="390" alt="2017-06-21 16 32 25" src="https://user-images.githubusercontent.com/2894860/27386686-3ccef5e8-569f-11e7-9dbb-5f3865e3227a.png">

**Comment by ronie-z-wave** [comment]
does the code device set the right icon type in vDev?
