### ISSUE TITLE
Device status not showed on widgets

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#239]
New style of icons I like!
You can control devices, but you don't see the status. Testet on Fibaro Dimmer 2 and Z-Wave.Me Plug.
On screenshot see:
Switch (#41)
Dimmer (39.0)
Dimmer (39.1)
Dimmer (39.2)
<img width="1190" alt="2017-06-27 12 42 13" src="https://user-images.githubusercontent.com/2894860/27581617-d28f1d9c-5b36-11e7-93e0-cb4691a4bc33.png">

**Comment by ronie-z-wave** [comment]
Please report what level is in vDev? and what level is in z-way data holder? Maybe there is a mistake during transformation or a type error ...

**Comment by aivs** [comment]
No problem on 1.7.0
