### ISSUE TITLE
v2.0.1 Report Problem is disfunctional

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#24]
The Report Problem says that the report was successfully sent, But:
1) I never reveive a copy in my own mail
2) I never receive a response on anything sent

So I guess it is disfunctional

**Comment by pz1** [comment]
I*'d rather remove it from the distribution if it isn't working at all now, and also won't be fixed shortly

**Comment by vades** [comment]
Will be fixed in the next release

**Comment by vades** [comment]
The copy of the report is send to a given e-mail.

**Comment by pz1** [comment]
Round trip confirmed for my rig. Thanks
