### ISSUE TITLE
Unable to upload room images

### ISSUE THREAD

**Issue by paaland** [Z-Wave-Me/zwave-smarthome#243]
Create 200x200 px jpeg image in Paint.Net, try to upload as room image (size is < 100 kb). No errors, but the image only appears as a white box.

Changed to gif and try again. This time only half the image is shown.

V1.7.0
Razberry

**Comment by vades** [comment]
Sometimes it happens if the image is corrupted. Try to reopen the image in the Image Editor and save it.

**Comment by karei90** [comment]
The whole process should be reworked in future, we should use native code to save the image.

**Comment by PoltoS** [comment]
Fixed an error with if \r\n is present in the binary representation of the image
