### ISSUE TITLE
Sensors add to the room header not Show Fullname at Mouse Over

### ISSUE THREAD

**Issue by jnissen** [Z-Wave-Me/zwave-smarthome#245]
Hello,
My device Names have many Chars. If I want to Select Sensors to the Room Header, I can´t see Full Device name.  MouseOver Shows "Remove". 

![grafik](https://user-images.githubusercontent.com/7793064/29429315-9317d0b4-8390-11e7-9158-73e2a2d08785.png)

**Comment by vades** [comment]
Fixed

**Comment by zwave-mke** [comment]
closed
