### ISSUE TITLE
Hide element not works after z-way restat

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#247]
I hid devices, but after restart they returned.
<img width="769" alt="2017-09-11 14 56 04" src="https://user-images.githubusercontent.com/2894860/30273486-d6b1a168-9701-11e7-946a-3b33ac9917cd.png">

BEFORE RESTART
<img width="1280" alt="2017-09-11 14 54 48" src="https://user-images.githubusercontent.com/2894860/30273507-e9a62ed8-9701-11e7-9818-6752bef663b6.png">

AFTER RESTART
<img width="1280" alt="2017-09-11 14 55 54" src="https://user-images.githubusercontent.com/2894860/30273513-f1f3197a-9701-11e7-9772-8d3805d0e15a.png">

**Comment by karei90** [comment]
does not occur on the latest version
