### ISSUE TITLE
V2.0.1 UI module configuration screen: empty line after checkbox title should be removed

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#26]
The blank line between the checkbox title and the actual checkbox should be removed to improve alignement in configuration screen elements:

![checkbox](https://cloud.githubusercontent.com/assets/7747627/8430633/261932e6-1f33-11e5-8127-3e34d77b163c.PNG)

**Comment by ronie-z-wave** [comment]
Which module?

**Comment by pz1** [comment]
The example is from my module XMLDevice:

https://github.com/pz1/home-automation/tree/develop/userModules/XMLDevice

**Comment by pz1** [comment]
Ah, I see the problem: For the checkbox I did use "label" as a key. I was not aware of the variant "rightLabel" that apparantly was created for checbox type fields. (Found it in the CodeDevice module)

I think (I have said that before) it would be good to have some documentation of the options in *module.json*.  How about a [json.schema](http://json-schema.org/) for this? Helps with formal debugging, and may be a smaller hurdle to take then writing a full document ;)

**Comment by pz1** [comment]
So I "worked around" the checkbox problem, which actually led to a better configuration.
I do have one more problem, possibly related to lack of knowledge about module.json syntax.
The point is the double stars ** in the headers of the other fields.

I can't find out why my screen has two of these stars, while the standard modules only have one.

**Comment by ronie-z-wave** [comment]
I think these are teh field levels ... they become more if you surround fields with another fields

**Comment by pz1** [comment]
Don't understand what I can do to get rid of it, other than leaving out the title, and only specify a helper text.
By the way, your OpenWeather app has the same "problem" as XMLDevice.

**Comment by ronie-z-wave** [comment]
aah ... its not 'field' but seems to be 'required:true' ... you have properties:{'required:true'} - first star and each property is also 'required:true' - second star ... same in my OpenWeather ... think we can/should hide this with css in SH UI

**Comment by pz1** [comment]
Fine thanks. As far as I am concerned the matter is closed. You may want to keep it open for a css fix
