### ISSUE TITLE
Can't add mobile device. QR code not loaded

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#260]
The QR code is not loaded or updated. Testet in Chrome, OSX, Retina display.
May be this happens because "Add mobile device" at the bottom and QR Code is not generated outside the window?
<img width="1221" alt="2018-02-09 13 48 01" src="https://user-images.githubusercontent.com/2894860/36024304-69dcc62e-0da0-11e8-84e2-33ef553cb7f1.png">

**Comment by mh-zwave** [comment]
This is allready fixed. 
We have moved the menu item to devices.
Also the qrcode code is no longer saved and is regenerated every time after entering the password.
This function will be available in version 2.3.7.
