### ISSUE TITLE
Unchecking Active checkbox in App settings is not working 

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#263]
On save "active" field is not sent to the server if active is False. It is sent when active is true.

Due to this can not disable MobileApp - it is not in the list of apps. Can open it via Manage devices, but can not disable from there.

**Comment by karei90** [comment]
Fixed in https://github.com/Z-Wave-Me/zwave-smarthome/commit/667b5be3af3caf508c98fb0db6a4a4e60355a25e
