### ISSUE TITLE
Button "Open updater" in the UI leads to a blank page with "Connection refused"

### ISSUE THREAD

**Issue by margru** [Z-Wave-Me/zwave-smarthome#270]
Cannot update the the firmware. After clicking on "Open updater" in the UI, a blank page opens with "Connection refused" error message. Accessing the UI from the local network.

Using v2.3.8-rc4, installed from the official image from z-wave.me, on RaZberry - RaspberryPi 3.

**Comment by PoltoS** [comment]
This is a known issue with Stretch. Please use console to run the update.

**Comment by margru** [comment]
OK, thanks.
