### ISSUE TITLE
Cannot install/update APPS FW V3.04

### ISSUE THREAD

**Issue by gilbi34** [Z-Wave-Me/zwave-smarthome#275]
Hello guys,

I can't install or update any apps !

HTTP error 500 from mongoose server

Installed  from  razberry-3.0.1_buster.img

and updated to v3.04.... same issue....

firmware : v3.0.4
Version UI: 1.10.2
built ; 20-01-2020 13:17:38
Raspbian Buster V10
Mongoose : 6.4

Is there a solution ?

**Comment by PoltoS** [comment]
known issue. please see https://forum.z-wave.me/viewtopic.php?f=3422&t=33273&p=86118&hilit=apps+fafiled#p86223

**Comment by gilbi34** [comment]
Great!

Many thinks Sergei

Gilbert
