### ISSUE TITLE
Possibly wrong interim position calculation of roller shutter actor

### ISSUE THREAD

**Issue by sebres** [Z-Wave-Me/zwave-smarthome#277]
Version: v3.0.6

I try to find a proper way to set-up a FIBARO Roller Shutter 3 (FGR-223), so that it will be possible to set also interim position of blind (e. g. 50%)

After I calibrated the device and manually adjusted parameters (154, 156, 157) because they were to high, it works ultimately fine by complete open/close of blind.
But if I select 50% starting from top position (99%, so top to bottom movement), it also stops by ca 50%.
If I do the same starting from bottom (0%, so move to top direction) it holds by ca. 30% so remains 2/3 closed.

I guess it happens because the movement of blend does not depend linearly on rolling of the shaft, so the direction seems to be important by the calculation of real position.

Is there some parameter or functionality I can use to adjust the curve (level. tendency, whatever) to force proper calculation shaft rotation time -\> real open position?
I don't think it is 3rd party issue (so FGR-223), because such parameter is hardly imaginable by actor self (it would depend on length of the blend, lamellae height, shaft radius and deviation of motor rotation depending of direction), so I guess it is simpler to control in z-wave.me.
At the moment basically time of up/down movements are the single parameters I can set in device (for instance 156 = ca. 1800 * 10ms to reach top and 157 = ca. 1550 * 10ms to reach bottom). Parameter 154 is just a latency to stop motor after end of movement and I set it to 0, because initial value 1s had confuse the calculation much more.

**Comment by sebres** [comment]
As an interim solution I increased parameter 156 (time for move up) to 2000 and decreased parameter 157 (time for move down) to 1400 together with adjustment of parameter 154 to 1.5s (to retard the stop of motor by moving down).
This causes that position 50% is reached now approximately correct in both directions.
But the issue is that the other positions (like 70% or 20%) are still incorrect if rolling from bottom to top direction.

**Comment by sebres** [comment]
It looks like a FIBARO (FGR-223) issue.
I guess it'd need some extra parameter(s), additionally to 156/157, describing the "curve" or some latency to follow non-linear movement (to consider radius of rolling shaft, depending on current position resp. to calculate mapping `real_pos% <=> motor_pos(‰)`).

Issue opened by manufacturer and was confirmed there:
> We're aware of this issue and we've already forwarded it to our engineers, who are currently working on resolving it as soon as possible. 

Although it can be also partially implemented in Z-Wave-Me (so it can be a nice RFE), but since FGR-223 "knows" its position internally and has a switch contacts `S1/S2` to move blend manually, it is not advisable at the moment - because if I use manual push button (S1/S2) starting from some interim position (from 90% or from 10%), after playing (down/up) using the Z-Wave, even manual movement can stop too early (as confused by wrong start position mistakenly "known" by FGR-223).
So if it was initially 50% (as assumed by controller), but 25% in the reality, manually triggered using button move up would let it stop by 1/4, so reaches 99% (assumed) by 75% in the reality.

Thus I'll close it here as 3rd party issue.

**Comment by PoltoS** [comment]
Thanks for confirming the issue is in the device. As for the RFE, you can do it using Code Device - create a virtual device that is binded to s real one via a formula written in JS

**Comment by sebres** [comment]
Good to know, Thx!
But I guess it'd not really help here, because the devices have wrong states stored in themselves (and at least manual usage via switches is then affected).
