### ISSUE TITLE
Missing "Off" button in switchMultilevelModal - file build.js

### ISSUE THREAD

**Issue by nostroff** [Z-Wave-Me/zwave-smarthome#279]
This is a request to make 2 changes in file build.js to support an "Off" button in the switchMultilevelModel widget (for mobile widget and non-mobile widget). Currently, there is "Full" button below the angle buttons. The proposed changes put the "Full" button above the angle buttons and the "Off" button below the angle buttons.

Also, can you please propagate the "Full" and "Off" button changes to the mobile app.

Thanks.

  $templateCache.put('app/views/elements/widgets/mobile/switchMultilevelModal.html',
    "<div id=switchMultilevelModal class=appmodal ng-controller=ElementSwitchMultilevelController ng-if=modalArr.switchMultilevelModal_m><div class=appmodal-in><div class=appmodal-header><span class=appmodal-close ng-click=\"handleModal('switchMultilevelModal_m', $event)\"><i class=\"fas fa-times\"></i></span><h3>{{widgetSwitchMultilevel.find.metrics.title}}</h3></div><div class=\"appmodal-body text-center\"><bb-alert alert=widgetSwitchMultilevel.alert></bb-alert><div class=\"app-row app-row-knob clearfix\"><div class=\"knob-col knob-ctrl\"><input value={{widgetSwitchMultilevel.find.metrics.level|getMaxLevel:widgetSwitchMultilevel.find.minMax.max}} class=\"dial widget-level-knob\" data-width=160 data-height=160 knob-step=widgetSwitchMultilevel.find.minMax.step knob-min=widgetSwitchMultilevel.find.minMax.min knob-max=widgetSwitchMultilevel.find.minMax.max knob-id=widgetSwitchMultilevel.find.id knob-data=widgetSwitchMultilevel.find.metrics.level knob-options=knobopt ng-model=widgetSwitchMultilevel.find.metrics.level myknob></div><div class=\"knob-col knob-btn\"><p>&nbsp; &nbsp;<button class=\"btn btn-info\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, widgetSwitchMultilevel.find.minMax.max)\" ng-bind=\"_t('lb_full')\"></button></p><button class=\"btn btn-primary\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, '+')\"><i class=\"fas fa-angle-up\"></i></button>&nbsp; <button class=\"btn btn-info\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, widgetSwitchMultilevel.find.minMax.max)\"><i class=\"fas fa-angle-double-up\"></i></button></p><p><button class=\"btn btn-primary\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, '-')\"><i class=\"fas fa-angle-down\"></i></button>&nbsp; <button class=\"btn btn-info\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, widgetSwitchMultilevel.find.minMax.min)\"><i class=\"fas fa-angle-double-down\"></i></button></p><p>&nbsp; &nbsp;<button class=\"btn btn-info\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, widgetSwitchMultilevel.find.minMax.min)\" ng-bind=\"_t('lb_off')\"></button> <button class=\"btn btn-default\" ng-if=\"widgetSwitchMultilevel.find.probeType == 'motor'\" id=\"btn_stop_{{ v.id}}\" data-ng-click=\"runCmd(widgetSwitchMultilevel.find.id + '/command/stop', widgetSwitchMultilevel.find.id)\" title=\"{{_t('lb_stop')}}\"><i class=\"fas fa-square text-danger\"></i></button></p><div class=\"btn-group btn-goup-block btn-goup-4\" ng-if=\"widgetSwitchMultilevel.find.deviceType == 'audioPlayer'\"><button class=\"btn btn-default btn-label-on\" id=\"btn_step_backward_{{ widgetSwitchMultilevel.find.id}}\" data-ng-click=\"runCmd(widgetSwitchMultilevel.find.id + '/command/previous', widgetSwitchMultilevel.find.id)\" title=\"{{_t('lb_step_backward')}}\"><i class=\"fas fa-step-backward\"></i></button> <button class=\"btn btn-default\" id=\"btn_play_pause_{{ widgetSwitchMultilevel.find.id}}\" data-ng-click=\"runCmd(widgetSwitchMultilevel.find.id + '/command/'+ (widgetSwitchMultilevel.find.metrics.pStatus == 'Play' && widgetSwitchMultilevel.find.metrics.pStatus != 'Stop' ? 'pause' : 'play'), widgetSwitchMultilevel.find.id)\" ng-class=\"widgetSwitchMultilevel.find.metrics.pStatus =='Play' || widgetSwitchMultilevel.find.metrics.pStatus =='Pause' ? 'btn-primary': 'btn-default'\" title=\"{{v.metrics.pStatus == 'Play' ? _t('lb_pause') : _t('lb_play')}}\"><i ng-if=\"widgetSwitchMultilevel.find.metrics.pStatus == 'Play'\" class=\"fas fa-pause\"></i> <i ng-if=\"widgetSwitchMultilevel.find.metrics.pStatus == 'Pause' || widgetSwitchMultilevel.find.metrics.pStatus == 'Stop'\" class=\"fas fa-play\"></i></button> <button class=\"btn btn-default\" id=\"btn_stop_{{ widgetSwitchMultilevel.find.id}}\" data-ng-click=\"runCmd(widgetSwitchMultilevel.find.id + '/command/stop', widgetSwitchMultilevel.find.id)\" ng-class=\"widgetSwitchMultilevel.find.metrics.pStatus =='Stop' ? 'btn-primary': 'btn-default'\" title=\"{{_t('lb_stop')}}\"><i class=\"fas fa-stop\"></i></button> <button class=\"btn btn-default btn-label-on\" id=\"btn_step_forward _{{ widgetSwitchMultilevel.find.id}}\" data-ng-click=\"runCmd(widgetSwitchMultilevel.find.id + '/command/next', widgetSwitchMultilevel.find.id)\" title=\"{{_t('lb_step_forward')}}\"><i class=\"fas fa-step-forward\"></i></button></div></div></div></div></div></div>"
  );

and

  $templateCache.put('app/views/elements/widgets/switchMultilevelModal.html',
    "<div id=switchMultilevelModal class=appmodal ng-controller=ElementSwitchMultilevelController ng-if=modalArr.switchMultilevelModal><div class=appmodal-in><div class=appmodal-header><span class=appmodal-close ng-click=\"handleModal('switchMultilevelModal', $event)\"><i class=\"fas fa-times\"></i></span><h3>{{widgetSwitchMultilevel.find.metrics.title}}</h3></div><div class=\"appmodal-body text-center\"><bb-alert alert=widgetSwitchMultilevel.alert></bb-alert><div class=\"app-row app-row-knob clearfix\"><div class=\"knob-col knob-ctrl\"><input value={{widgetSwitchMultilevel.find.metrics.level|getMaxLevel:widgetSwitchMultilevel.find.minMax.max}} class=\"dial widget-level-knob\" data-width=160 data-height=160 knob-step=widgetSwitchMultilevel.find.minMax.step knob-min=widgetSwitchMultilevel.find.minMax.min knob-max=widgetSwitchMultilevel.find.minMax.max knob-id=widgetSwitchMultilevel.find.id knob-data=widgetSwitchMultilevel.find.metrics.level knob-options=knobopt ng-model=widgetSwitchMultilevel.find.metrics.level myknob></div><div class=\"knob-col knob-btn\"><p>&nbsp; &nbsp;<button class=\"btn btn-info\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, widgetSwitchMultilevel.find.minMax.max)\" ng-bind=\"_t('lb_full')\"></button></p><p><button class=\"btn btn-primary\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, '+')\"><i class=\"fas fa-angle-up\"></i></button>&nbsp; <button class=\"btn btn-info\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, widgetSwitchMultilevel.find.minMax.max)\"><i class=\"fas fa-angle-double-up\"></i></button></p><p><button class=\"btn btn-primary\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, '-')\"><i class=\"fas fa-angle-down\"></i></button>&nbsp; <button class=\"btn btn-info\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, widgetSwitchMultilevel.find.minMax.min)\"><i class=\"fas fa-angle-double-down\"></i></button></p><p>&nbsp; &nbsp;<button class=\"btn btn-info\" ng-click=\"setExactCmd(widgetSwitchMultilevel.find, widgetSwitchMultilevel.find.minMax.min)\" ng-bind=\"_t('lb_off')\"></button></p></div></div></div></div></div>"
  );

**Comment by PoltoS** [comment]
Hi! This task is already in work, but we will check your templates too. Thank you!

@Xel4ek Please compare with our latest changes
