### ISSUE TITLE
Ambiguity in message "Device has no configuration" 

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#28]
This is a bit confusing for users. It looks as if there is something wrong/missing with the device description record.  I think it shoudl actually say: **Device has no configurable parameters**. That would make more sense if including for example a Duwi wall plug
But then there is something odd. I looked through the PepperOne data base where I noticed that if there is a battery device, the wake-up "parameter" actually is not a parameter in the Z-Wave sense.
So to cater a possible wake-up setting I suggest:
**Device has no (other) configurable parameters**

![stellaz config](https://cloud.githubusercontent.com/assets/7747627/8475284/3bda73da-20b7-11e5-9d97-bc9452df1017.PNG)

**Comment by PoltoS** [comment]
@vades The message seems to be shown on no ZDDX selected and it should be "No Device Description Selected" instead (with a link to Interview Tab or even with a button to select it.

@aivs We need to fix translation too

**Comment by vades** [comment]
The message is now shown as INFO text with link to the Interview tab.
![z wave expert ui-issue-28](https://cloud.githubusercontent.com/assets/1451741/8613714/4b6c86c2-26e2-11e5-8f00-48bd497df7fb.png)
