### ISSUE TITLE
Door locks were reported not to work in SH UI

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#30]
Please check.

http://forum.z-wave.me/viewtopic.php?f=3422&t=21766&p=57103#p57103

**Comment by ronie-z-wave** [comment]
fixed with https://github.com/Z-Wave-Me/zwave-smarthome/commit/8c148f564fe3bc66319c6e37612175a4d0d02942

How will we handle the ct101 thermostat? Unfortunately we haven't one here for testing ... so we can't find out wether it is an ui problem or not ...
