### ISSUE TITLE
Dummy device have no "hidden" flag in the UI.

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#31]
As some other devices too

**Comment by ronie-z-wave** [comment]
Is it correct, that this only applies to devices produced by instances? Of course maybe a hint or message will be better than only hiding 'hidden'. We had the opinion that hiding this devices does not make sence because if you dont want to show it you can deactivate/remove the apps instance.

**Comment by PoltoS** [comment]
Well, I might want a Dummy in some logics, but don't want to see it on my screen.

Same applies to other devices produced by modules like Sonos (it makes two devices per Sonos box, but you might hide some of them) or EnOcean.

**Comment by PoltoS** [comment]
So, please make it for all devices

**Comment by ronie-z-wave** [comment]
Makes sence, we'll do it.

**Comment by vades** [comment]
Hide or Unhide device is possible only for Z-Wave devices. This is Christians requirement
