### ISSUE TITLE
Where modules Z-Wave and Enocean ?

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#36]
I ran the latest version UI Smarthome and I can't see Z-Wave module in "Local Apps" and "Active".
Where to find Z-Wave settings ?

**Comment by ronie-z-wave** [comment]
Please go to 'My Settings' and activate the checkbox beneath 'Expert View'. After that you should see everything like before ;)

**Comment by aivs** [comment]
ok, it doesn't work, after clicking the save button page reloaded, and checkbox is cleared.
 In "Local Apps" and "Active" Z-Wave module doesn't appear.

I think this checkbox not good idea. If you want to hide Z-Wave configuration from modules list, create new tab "Z-Wave Configuration" in "Z-Wave network" section. 
<img width="1280" alt="zwaveconf" src="https://cloud.githubusercontent.com/assets/2894860/8802225/bd8728b8-2fc8-11e5-899c-c747e6163bed.png">

Again, the difficulties begin with the search settings.

**Comment by jbehuet** [comment]
:+1: I find too it's more simple like this. And I've the same problem with checkboxes

**Comment by pz1** [comment]
I had hoped this had been solved in 2.0.2rc1-26-xxxx. Or is it more complex than just fixing the checkbox that does not seve its setting? On my test rig I can't disable/enable Zwave bindings now
