### ISSUE TITLE
Everywhere in UI used a different color for the similar tasks. Need unification.

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#37]
I suggest using the same color as the button colors on the widget:
1) Highlighted
* Highlighted-backgound: #E5E5E5  (light gray)
* Highlighted-text/icon: #BB1823  (red)
*Button on widgets don't change Highlighted-text color - it's OK.*

2) Selected
* Selected-background: #7493b9 (light blue)
* Selected-text/icon: #FFFFFF (white)
    
The drop-down list (maybe in other places too)  is used the highlighted color #DDDDDD (dark gray), need #E5E5E5 (light gray). Origin colors
<img width="1280" alt="highlightcolor" src="https://cloud.githubusercontent.com/assets/2894860/8799038/cc265222-2faf-11e5-918f-cc98bb7e6002.png">

Replace selected color from #DDDDDD (dark gray) to #7493b9 (light blue), and selected text from #BB1823  (red) to #FFFFFF (white). My colors
<img width="1280" alt="selected" src="https://cloud.githubusercontent.com/assets/2894860/8799742/11a27560-2fb5-11e5-9e5a-d07ab7343809.png">
My colors
<img width="1280" alt="2015-07-21 14 18 15" src="https://cloud.githubusercontent.com/assets/2894860/8799745/19bb523a-2fb5-11e5-875c-fef8c0b67618.png">
My colors
<img width="1280" alt="2015-07-21 13 23 56" src="https://cloud.githubusercontent.com/assets/2894860/8799748/2234a0ba-2fb5-11e5-8ad2-e1864c9c7a26.png">

Before. Origin colors
<img width="1280" alt="before" src="https://cloud.githubusercontent.com/assets/2894860/8799793/955e5f72-2fb5-11e5-816b-b4c197f1c311.png">

After. My colors
<img width="1280" alt="after" src="https://cloud.githubusercontent.com/assets/2894860/8799796/9b3a6332-2fb5-11e5-9b42-7d211de6cd61.png">

**Comment by vades** [comment]
This is a good idea and I changed colors (a little bit). But colors should correspond also to user profile color (user can select a different color). So we will keep it simple.
![screen-4](https://cloud.githubusercontent.com/assets/1451741/8845955/82ae8784-3123-11e5-834a-c3589054d38d.png)
![screen-3](https://cloud.githubusercontent.com/assets/1451741/8845956/82b23618-3123-11e5-9ffd-adfa57874594.png)
![screen-2](https://cloud.githubusercontent.com/assets/1451741/8845958/82b44c5a-3123-11e5-8721-adb68c4da67d.png)
![screen-1](https://cloud.githubusercontent.com/assets/1451741/8845957/82b3ff3e-3123-11e5-8265-52f11df583d0.png)

**Comment by aivs** [comment]
I like it!!
