### ISSUE TITLE
Modules: Unchecking the "Active" checkbox does not deactivate a module

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#38]
![active](https://cloud.githubusercontent.com/assets/7747627/8800748/9c806890-2fb5-11e5-8805-a717fb9e42e1.PNG)
I did an uncheck followed by a Save action. The module was still active. A bit counter-intuitive.

**Comment by PoltoS** [comment]
The module was certainly unloaded, but it does not unload the code injected by the module. We need to think about it a bit more - may be use closures.

**Comment by pz1** [comment]
It is still there in v.2.1.1
