### ISSUE TITLE
Index.js access to icons in automation/userModules/htdocs

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#4]
Two months ago I [suggested on the forum](http://forum.z-wave.me/viewtopic.php?f=3422&t=21356&hilit=+icon#p55546) to make module related icons accesible form folder *automation/userModules/htdocs*.
As the icon for the module itself can be read from that folder I tried to display a couple of status icons from that folder with my **index.js** file. Should that be possible at all, and if not would it not be a good idea to allow that. That would allow for simple distribution of module bound icons.

**Comment by pz1** [comment]
This issue is essentially the same as https://github.com/Z-Wave-Me/home-automation/issues/226
Assuming that this issue survives I'll close 226
My userModule needs to display status icons, that are distributed with the module. At present I have to move them manually to the z-way-server/htdocs directory. That is inconvenient

**Comment by pz1** [comment]
In the meantime I have progressed a bit on this since I found that it should be possible using something like:
> icon: "/ZAutomation/api/v1/load/modulemedia/**ModuleName**/**IconName**.png"

to retreive the images from the htdocs folder of the userModule. 

Guess I am missing something here, since the icon is not displayed in the UI

> icon = "/ZAutomation/api/v1/load/modulemedia/SolQoS/" + status + "58px.png";
> self.vDev.set("metrics:icon", icon);

(Before I had the icons in z-way-server/htdocs/user. That did work fine, but was awkward a.o. because of updates)

**Comment by pz1** [comment]
Got it finally working by prefixing it with the **http://raspberrypi_IP:8083**. 

Is that intended use? If yes, the issue can be closed

**Comment by pz1** [comment]
> Got it finally working by prefixing it with the http://raspberrypi_IP:8083. 

Just installed v2.0.2-rc3 to find out this work-around is no longer functioning.

**Comment by PoltoS** [comment]
Nothing changed. Need more info to uunderstand the problem

**Comment by pz1** [comment]
Don't know what more I could tell
