### ISSUE TITLE
Second instance of sensor binary doesn't have a icon "Sensor Binary"

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#40]
Device: Fibaro Universal Sensor with 2 binary sensors
<img width="1179" alt="2015-07-23 21 28 45" src="https://cloud.githubusercontent.com/assets/2894860/8858788/2879a85c-3182-11e5-86e1-fbeb78acb976.png">

**Comment by vades** [comment]
Some devices have no icon defined eg.: 
"metrics": {"level": "on","icon": "","title": "Light Scene 100"}
If icon is empty is replaced with the placeholder icon
Can you please check JSON http://IP:8083//ZAutomation/api/v1/devices/Your_Device_ID node "metrics"?

**Comment by PoltoS** [comment]
Check why icon field is empty for the seconf device.

**Comment by ronie-z-wave** [comment]
Some solution or has something changed?
