### ISSUE TITLE
Must editing devices really be so painfull?

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#41]
To control my StellaZ thermostats with scenes I had first to manually craft 40 coded devices to set the different operating modes of the thermostats. So I defined all those and gave them nice meaningfull names.
Next step is to define the scenes. It was sheer horror to see a dropdown list of meaningless identifiers named Code device 12 -Code device 43, instead of my given names.
It is a very frustrating chore to manually copy and paste all the names from the definition to the elements in smarthome, before I can finish the scenes. Not a bonus point :(

**Edit**: And the same goes on for selecting Scenes in Chedules Scene module. Only Scene numbers Light Scene 44 etc. Even after having renamed the Smarthome scene elements to meaningful names.
**Edit2**: In the morning I did find these given Scene names in the dropdown menu. Takes apparantly some more time to settle.

**Comment by PoltoS** [comment]
We have a lot of debates on this... May be you have an idea how to do it easily.

Problems:
1) a module can have many devices created
2) user can rename the module after initial creation - should we rename device too?
3) user can rename device after creation - should we rename the module? and if there are many devices created?
4) module can create 0, then 1 and then more devices (like Z-Wave module during inclusion), so the "renaming" logic should tolerate all these cases where module can have one or many devices created.
5) we don't want to add this "renaming" logic in each module - it should work transparent for all modules and all devices.

One helpful change could be: if module is renamed and produced devices have their "default" names, they can be renamed with module prefix.

Another case is to handle the renaming in the UI, not in the backend - in this case UI can check that there are devices created by the module and propose to rename them.

**Comment by PoltoS** [comment]
@aivs is pushing this feature for a long time - let's discuss together.

**Comment by pz1** [comment]
I've send you both a short preliminary note via email

**Comment by aivs** [comment]
I feel the pain and suffering!
Pieter I saw your message, I'll give a full response later.

**Comment by pz1** [comment]
> I feel the pain and suffering!
Well it is not that bad, as long as we can learn from the experiences and make progress. Interoperability just is difficult

**Comment by pz1** [comment]
In v2.1.1 I did create a new Scene, which I gave a name at creation time. In the picklist for logical rules and scenes it persistently displays as **Light Scene 51** the given name is not available.
