### ISSUE TITLE
Configuration of the device doesn't stop if interview has failed

### ISSUE THREAD

**Issue by NilsBohr** [Z-Wave-Me/zwave-smarthome#42]
If by somekind of a reason the interview didn't complete well, the configuration page in the Smarthome UI doesn't ever end.

I think it can be improved.

![expert](https://cloud.githubusercontent.com/assets/5468659/8928391/da2cf96c-3526-11e5-935a-6cc4897a2f83.png)

![smarthome](https://cloud.githubusercontent.com/assets/5468659/8928397/e0e378b2-3526-11e5-9f13-80099eb70c14.png)

**Comment by vades** [comment]
The obligatory question: What  firmware version (release) do you have?
From release v2.0.1 - if the interview fails or is not complete this  alert displayed:
"Device found but the configuration is not complete"

**Comment by NilsBohr** [comment]
It's version is v2.0.2-rc1-12-g8364373
Issue present.

![controller_version](https://cloud.githubusercontent.com/assets/5468659/8981936/21fdf21a-36c5-11e5-9e04-c9db3b78172b.png)
