### ISSUE TITLE
The sensor devices doesn't update when triggered

### ISSUE THREAD

**Issue by NilsBohr** [Z-Wave-Me/zwave-smarthome#43]
Really frustrating problem. All the sensor devices doesn't update when received an unsolicited report.

To reproduce an error:
- take a device with a Sensor Binary CC
- included it in the network
- trigger an unsolicited report  from it (f.e. door/window sensor)
- watch in the interface. You may have 3 options: 
          1) The status updates - you are lucky - try again
          2) The status updates only in one side (off -> on, but not on -> off)
          3) The status doesn't update
![ei-trigger_1](https://cloud.githubusercontent.com/assets/5468659/8928624/531f9b12-3528-11e5-8c2c-2153d717bca8.png)

- Now press the refresh page button. The status shall be updated now.

![ei-trigger_2](https://cloud.githubusercontent.com/assets/5468659/8928669/97debb48-3528-11e5-8d61-227df2b60205.png)

**Comment by vades** [comment]
What  firmware version (telease) do you have?

**Comment by NilsBohr** [comment]
Version v2.0.2-rc1-12-g8364373

![controller_version](https://cloud.githubusercontent.com/assets/5468659/8981958/4dd85632-36c5-11e5-8ddb-26be50bf3f4b.png)

**Comment by PoltoS** [comment]
@NilsBohr fixed?

**Comment by aivs** [comment]
Works! in 2.1.1
