### ISSUE TITLE
Device settings page should have device ID

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#45]
Otherwise it is hard to get for users. Needed to be used in API

**Comment by vades** [comment]
What exactly do you mean with "... device ID"?
Page device setting has already device ID

![issue-45](https://cloud.githubusercontent.com/assets/1451741/9034654/adaffcc2-39d1-11e5-9304-c9f25c0ef30e.png)

**Comment by PoltoS** [comment]
I'm about vDev - not Z-Wave devices. People need to be able read somewhere vDev ID (not in URL only). They need to use it in modules.

**Comment by vades** [comment]
OK - vDev = Elements :-)
We have naming conventions:
Elements -from ZAutomation/api/v1/devices
Devices - Z-Wave devices
Apps - from ZAutomation/api/v1/modules or Online source

![issue-45](https://cloud.githubusercontent.com/assets/1451741/9037025/48741256-39e7-11e5-81f4-e1428909f6b6.png)

**Comment by PoltoS** [comment]
Thanks!
