### ISSUE TITLE
Please merge Alpaca fix in our branch

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#46]
This one:

https://github.com/SuperSeb92/alpaca/commit/fbb51cf91f2561573f96b770852ad315ebd040a9

This prevents in CodeDevice to show updateOnAction for Switch Binary/Multilevel types

**Comment by vades** [comment]
I can not merge the Alpaca fix. I have the package with min version only.
Can you send me the package with merged with this fix? Or better - create branch with Alpaca updates for SmartHome.

**Comment by PoltoS** [comment]
Where you took the Alpaca? May be you attach it using git submodules? Or keep as is, just update to latest

**Comment by vades** [comment]
Hi,
after updating to latest alpaca 1.5.13 I got this error:
{"message":"The compiled template: 
bootstrap-edit:view:bootstrap-edit:container failed to execute: a.call 
is not a function"}
and no form is shown.

I took alpaca from Niels (only min version) and he has a few weeks holiday.

Martin

Am 03.08.2015 um 16:33 schrieb Poltorak Serguei:

**Comment by vades** [comment]
Updated to 1.5.13
