### ISSUE TITLE
In empty room show dialog of device adding to room

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#47]
If there is no devices in the room, then show room settings from or show a dialog of device adding to room. 
I think label "Include device" is not appropriate.

<img width="1280" alt="2015-08-05 10 51 19" src="https://cloud.githubusercontent.com/assets/2894860/9080850/3abca414-3b60-11e5-993c-71557e3b22e8.png">

**Comment by vades** [comment]
- If a room has no element assigned is not clicable.
![rooms](https://cloud.githubusercontent.com/assets/1451741/10453882/5060407e-71b0-11e5-892e-329ecb24ae38.png)
