### ISSUE TITLE
Can't set Dimmer value to 0 in Logical Rules

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#48]
Latest z-way-server-RaspberryPiXTools-v2.0.2-rc2-beta-5-g7a141a0.tgz 
In Logical Rules for dimmer cant' set value 0, it is not saved. Value 1 - 99 saved without problems.
<img width="1280" alt="2015-08-11 14 44 25" src="https://cloud.githubusercontent.com/assets/2894860/9197074/d78abbe0-4039-11e5-90a0-8a1b621a48bd.png">

**Comment by PoltoS** [comment]
@vades seems to be same problem I fixed recently in alpaca (a month ago)

**Comment by vades** [comment]
I've upgraded Alpaca to the latest 1.5.13 Seems doesn't works :-)

**Comment by vades** [comment]
... but on my site it works - you can save the "0" value with the latest Alpaca 1.5.13.
![issue-48](https://cloud.githubusercontent.com/assets/1451741/9221706/a6fbfcf6-40ec-11e5-8023-fbf84da0c2e5.png)

**Comment by PoltoS** [comment]
@aivs please confirm and close

**Comment by aivs** [comment]
Works! in 2.1.1
