### ISSUE TITLE
In widget settings show Name of module INSTANCE. Now showing only module name

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#49]
When created 10 widgets in a row, it's hard to understand which module instance created the widget.
Now in widget settings showing only module name, but need to show "module instance name + module name", like: "Motion sensor in Hall - Security Mode"
<img width="1280" alt="2015-08-11 23 42 21" src="https://cloud.githubusercontent.com/assets/2894860/9210213/a046f8de-4083-11e5-919c-23ae07da31d6.png">

The best way, if module instance generate only one widget, then name this widget as a module instance.

**Comment by vades** [comment]
![issue-49](https://cloud.githubusercontent.com/assets/1451741/9218534/95076c60-40d3-11e5-807a-13978eb5c0bc.png)
![issue-49-2](https://cloud.githubusercontent.com/assets/1451741/9218533/95040336-40d3-11e5-9062-1fa200a8c1c4.png)
