### ISSUE TITLE
Dashboard empty after update

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#5]
I've updated z-way from rc25 to rc37, and now I use smarthome UI, but I cant see devices on dashboard. In JS log I see that devices is updated. If in device settings I choose "Add to dashboard" (on screenshot I added RGB to dashboard), I will see this device on dashboard, but the devices added using the previous  Z-Way HA UI I cant see.   
![2015-06-04 0 01 24](https://cloud.githubusercontent.com/assets/2894860/7971360/e53e102a-0a4c-11e5-97dc-6445e8c81362.png)

**Comment by vades** [comment]
Fixed
