### ISSUE TITLE
V2.0.2-RC3 Zwave module has disappeared

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#50]
Zwave module has disappeared. Can no longer disable/enable nor change port. Couple of other things that did work under v2.0.2-rc1 do not work any more.

**Comment by PoltoS** [comment]
Can you give more info? Or access

**Comment by pz1** [comment]
While fiddling to give you remote access, I noticed that the checkbox was again on my screen. I has been looking for it, and even restarted FF. Anyhow that setting is back and the problem is solved
