### ISSUE TITLE
On online app installation from app info screen (not from the list) the installation status is not updated.

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#51]
If done form the list everything is ok, status updated as expected.

Would be cool to also allow install from file. And also write some "howto" on how to add your own module to the store.

**Comment by pz1** [comment]
You could consider the solution that Synology has for its Apps. In their plugins configuration you can specify a download path.
![sources](https://cloud.githubusercontent.com/assets/7747627/9606503/016fb3d0-50c4-11e5-8d13-18bac14a5914.PNG)

**Comment by zwave-mke** [comment]
we now use a token-system

**Comment by pz1** [comment]
Fine
