### ISSUE TITLE
zway 2.1.1, Wrong link to Expert UI in Smarthome start screen

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#54]
zway 2.1.1, Wrong link to Expert UI in Smarthome start screen
<img width="1280" alt="2015-09-04 10 26 14" src="https://cloud.githubusercontent.com/assets/2894860/9682849/20d0a544-5313-11e5-8b4e-260b8a9be8c4.png">

**Comment by ronie-z-wave** [comment]
Please give me some more informations e.g. how this link looks like ... 

this simple anchor tag looks like this: <a href="/expert" target="_blank">Go to Expert UI!</a> and usually this refers to http://MYRASP:8083/expert

**Comment by PoltoS** [comment]
Niels, looks like a problem with ". Please check

**Comment by ronie-z-wave** [comment]
hmm think this should be correct because it is <a href=\\\"/expert\\\" target=\\\"_blank\\\"> in config.json ... works fine till yet, didn't change anything since v2.0.1 ...

**Comment by pz1** [comment]
Just my 2cts:
Wouldn't it suffice if you made a textual reference to this dropdown menu?
![expert](https://cloud.githubusercontent.com/assets/7747627/9715222/a14b5c4e-555e-11e5-9431-da834d380053.PNG)

**Comment by ronie-z-wave** [comment]
argh -.- ... I didn't see the red elipse ... yup looks like problem with " ... 

@pz1: looks like an alternative to this ;)

**Comment by ronie-z-wave** [comment]
changed in /defaultConfigs
https://github.com/Z-Wave-Me/home-automation/commit/7ce2b1e686497d878f5b5f15a197a0bd7578ef47
