### ISSUE TITLE
Don't use metrics:icon to detect device type. Use deviceType field instead

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#56]
If icon of the vDev changes from multilevel to anything else, the widget will change. This is very bad, since icon just refers to a picture and not to widget view.

**Comment by maros** [comment]
Only multilevel switches with the icon 'blinds' will have the Up/Down buttons. Why not add a secondary device type (similar to probeTitle) that indicates if the multilevel device is a blind, window, dimmer, ... ?

**Comment by vades** [comment]
Icon section will be completely factored
