### ISSUE TITLE
For Login button and Login field need to use different translations

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#61]
In Russian translate placeholder for login field and text on login button are different.
Need to add new property in lang files, something like:
"lb_enter":"Login",
"lb_enter":"Вход",
<img width="646" alt="2015-10-09 13 18 41" src="https://cloud.githubusercontent.com/assets/2894860/10391780/f69945a0-6e89-11e5-84a2-841ef42de792.png">

**Comment by PoltoS** [comment]
так добавь ;) git ведь! 

----- Исходное сообщение -----

**Comment by aivs** [comment]
А точно, я могу

**Comment by aivs** [comment]
Closed with commit f39143c75fd2328b33312f15b5eecd5f5088e772
