### ISSUE TITLE
Online apps: Mention version number?

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#62]
I am aware that the online Apps in v2.1.1 still is experimental. However, I think it would be good if the version number of the online APP is shown in the overview. Elaborating on that, one could also consider to mention if the APP store module is newer than the installed version.

**Comment by PoltoS** [comment]
We should mark apps using color: if online app is same version (green), if newer - (yellow) or other.

**Comment by pz1** [comment]
Great!

**Comment by pz1** [comment]
I have seen some green background color with v2.2.1-rc3. So I assume this is solved
As far as I am concerned you may close this issue
