### ISSUE TITLE
Add room from Room tab

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#7]
Please add button "Add Room" into Room Tab, 
![2015-06-04 19 36 56](https://cloud.githubusercontent.com/assets/2894860/7989355/9b3405ca-0af1-11e5-97c5-a44d78f36d38.png)

**Comment by vades** [comment]
Done
![add-new-room](https://cloud.githubusercontent.com/assets/1451741/8225556/93fda5a4-1596-11e5-80be-e0a1a5ccc219.png)
