### ISSUE TITLE
v2.1.2-rc2 Zwave configuration screen 

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#70]
![zwaveapi](https://cloud.githubusercontent.com/assets/7747627/10817188/91f93fb0-7e38-11e5-97fb-021ddf785821.JPG)

It is unclear to me to what "/ZWave//*" refers.

**Comment by PoltoS** [comment]
missing escape of < and > tags. Fixed 3874480

**Comment by PoltoS** [comment]
BTW, this /ZWave/zway/* API is needed only if you have multiple dongles. New Expert UI seems to support it already. Used for multi-frequency environments like Malaysia or Hong Kong
