### ISSUE TITLE
Sort apps by name

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#72]
Or explain current sort order

**Comment by ronie-z-wave** [comment]
Apps are already by name. Beginning top-left from left to right.

**Comment by Genius72** [comment]
Is it possible to sort the apps in "active" tab?
Currently they are randomly mixed.

**Comment by ronie-z-wave** [comment]
Will be sorted by name in next version, too.

**Comment by aivs** [comment]
Why by name?
Active apps should be sorted by adding time. Last added on bottom. When you rename the module is not jumping on another place.

**Comment by ronie-z-wave** [comment]
ah ... sry of course by creation time :) 
That wasn't my last info, now I'm up to date.
