### ISSUE TITLE
What is the difference in colors of association?

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#75]
![imgo](https://cloud.githubusercontent.com/assets/3664383/11115792/03f5642a-893f-11e5-9a2d-7919352ca275.jpg)
![imgo1](https://cloud.githubusercontent.com/assets/3664383/11115794/079a7b2e-893f-11e5-8d25-21fbcbb29985.jpg)

**Comment by PoltoS** [comment]
gray is not stored yet on the device?

**Comment by christianpaetz** [comment]
this is expert UI and as legend in next release
