### ISSUE TITLE
Write up a short summary on how to translate Z-Way

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#76]
Is this enough to add a new language?

1) Add translation in translations/*.xml
2) Translate automation/lang/en.json
3) Translate automation/modules/*/lang/en.json
4) Translate htdocs/smarthome/dist/app/lang/en.json
5) Add the language in lang_list array in htdocs/smarthome/dist/app/config.js
6) Translate htdocs/expert/dist/app/core/lang/en.json
7) Add the language in lang_list array in htdocs/expert/dist/app/core/config.js

Once corrected, I'll post it on our RaZberry site

**Comment by christianpaetz** [comment]
done and available

**Comment by pz1** [comment]
> done and available
Where?
