### ISSUE TITLE
Suggestion: Use scene icons for scenes in smarthome/#/elements

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#77]
If there are many elements, the view on the elements page is hard to handle. The selections do help, but sometimes it is hard to grasp the right category. I think choosing the existing scene icon for scenes would make it a bit easier for users.

Elaborating on that, it would be nice if in the future if users of the **code device** app could also pick an appropriate icon from the existing collection

**Comment by vades** [comment]
We're going to prepare a feature "Upload custom icon"

**Comment by pz1** [comment]
@vades 

> We're going to prepare a feature "Upload custom icon"

Can we have an approximate release date for that ?

**Comment by vades** [comment]
This feature is in the latest release. But exact date unknown

**Comment by pz1** [comment]
Thanks for the update. Now I know what to answer on the forum where related questions are popping up once in a while.
Pieter
