### ISSUE TITLE
Upgrade from v2.1.1 to v2.1.2-rc17-44-gd59bf28 messed up all devicenames again

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#78]
I thought this had been solved! Now again I have to rename everything. Also very annoying that the link to the Expert UI has been hidden under devices. Two more steps to go. Secondly the ExpertUI window replaces the SmartHome view. I need those to sit side by side for debugging. Please do not make it more difficult than is already is.

*update 20151227* On further thinking, the actual question is how do you think to prevent this issue from happening again with a new release

**Comment by vades** [comment]
- Link to ExpertUI remains in the devices.
- ExpertUI is loaded in the  new tab.
