### ISSUE TITLE
Local user gets login screen

### ISSUE THREAD

**Issue by maros** [Z-Wave-Me/zwave-smarthome#79]
I do have the following setup

* a local user ("Local User (access only via localhost / 127.0.0.1)")
* Nginx running on 443 proxying to localhost:8083 (therefore all requests coming via the proxy should not need a zway authentication since they are handled by the local user)
* Authentication is handled by nginx via user certificates

Accessing the automation API (eg. https://myhost/ZAutomation/api/devices/ZWayVDev_zway_xxx) via the proxy works fine, and I don't have to authenticate. However, when accessing the smarthome UI (eg. https://myhost/smarthome/#/elements/dashboard/1 )  i am presented the login screen. Furthermore ZWaveApi also returns a 401.

**Comment by maros** [comment]
https://github.com/Z-Wave-Me/zwave-smarthome/pull/80 fixes this issue

**Comment by maros** [comment]
After accessing the smarthome UI with a local user, I noticed that many permissions are wrong. eg. cfg.role_access.config_rooms: [1,3]. I was wondering why the local user needs permissions for managing rooms? Changing these permissions to admin-only worked for me, but I'm not sure how it would affect other usages of the local user role?

**Comment by maros** [comment]
This PR requires also changes in home-automation to work properly. I believe that the PR i made to home-automation somehow got lost:
https://github.com/Z-Wave-Me/home-automation/pull/301/commits

**Comment by PoltoS** [comment]
We have merged this in v2.2.1 and changed a bit to adopt for local user
