### ISSUE TITLE
RC35 problem with corrupted admin account

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#8]
According to a forum post, there seems to be a [problem with a corrupted admin account](http://forum.z-wave.me/viewtopic.php?f=3419&t=21672) in RC35 (and may be before). It is unclear how the account can be restored/replaced.

**Comment by ronie-z-wave** [comment]
hmm ... one thing he could do is to clear profile array in config.json ... so he gets a new 'clean' admin profile ... but of course this assumes some knowledge ... would be interesting to know which version he has used before ... If I understand corectly he logged in with admin:admin ... changed the password and was not able to log in again, right?

**Comment by ronie-z-wave** [comment]
I know in version minor rc38 ... UI was not synchron with HA ... if he updates to v2.0.1-rc43 or next time to v2.0.1 this will be reseted automaticly, so he should be able to login with login: loginName and password loginName ... after that he should be able to change it without problem ... also creating/editing other users should be no problem
