### ISSUE TITLE
List elements error

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#82]
![screenshot from 2015-12-13 17 48 00](https://cloud.githubusercontent.com/assets/3664383/11767526/b5635ad8-a1c1-11e5-9eb3-1a82809e3f1a.png)

v2.2.0, added second Z-Way instance and included some devices in it. Looks something is duplicated

**Comment by PoltoS** [comment]
Can provide access if needed

**Comment by vades** [comment]
This happens when two devices from /ZAutomation/api/v1/devices have same ID.

**Comment by PoltoS** [comment]
I wander how this happened in my installation. Same ddvice ID? Or same nodeId?

Anyway, thjs should not produce any crash. We need to make more senity checks in the code

**Comment by vades** [comment]
Sometimes is duplicated device ID. This problem is resolved by adding _uniq() or can be also resolved by Angular filter ng-repeat="v in dataHolder.devices.collection| unique: 'v.id'". This is a patch for front-end. But every device MUST have an unique ID

**Comment by vades** [comment]
Please test it

**Comment by ronie-z-wave** [comment]
I'm not sure about this but sometimes (rarely) my raspi has the same problem, often a restart helps to clean up device.json ... strange thing is that sometimes it is only duplicated in ui and sometimes (even rarer) it is duplicated in config.json ... I suppose it could have to do with active singleton apps. It seems to occur - but not always, thats why I suppose this could be the problem - if you try to update and/ or reinitialize such an app ... I'll have a look at this
