### ISSUE TITLE
Not all widgets showed in List in module

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#85]
As example, in module GroupDevices I want to select all 5 dimmer, 2 real dimmers and 3 dummy device dimmers. But some times I see only 3 dummy devices, and some times only 2 real dimmers, don't see 5 devices together. All devices have type "switchMultilevel".
<img width="531" alt="2015-12-22 18 30 14" src="https://cloud.githubusercontent.com/assets/2894860/11958937/bbc2c686-a8db-11e5-94b8-5929687cefae.png">
<img width="1175" alt="2015-12-22 18 35 34" src="https://cloud.githubusercontent.com/assets/2894860/11958940/bf769140-a8db-11e5-8fe3-14e12fd412e2.png">

**Comment by ronie-z-wave** [comment]
Will have a look at this.

**Comment by ronie-z-wave** [comment]
Please check, should work now. e997df8b424669c5ddfd262502ea8b9350cffa73

**Comment by ronie-z-wave** [comment]
@aivs please check https://github.com/Z-Wave-Me/home-automation/commit/08617c7b24e97ae301fb3f1704f5db6d0bdcfb87
