### ISSUE TITLE
Ui scaling on Android

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#86]
Please doublecheck this
http://forum.z-wave.me/viewtopic.php?f=3419&t=22610

**Comment by vades** [comment]
Try to Refresh Chrome Cache: http://refreshyourcache.com/en/chrome-android/
Should resolve this problem.

**Comment by michapr** [comment]
I have refreshed the Cache of course before writing about it.
Then I have changed the size, fonts etc. at different places in tablet, so that it is working.

Bad is - do not find every place to go back now :(  ... so can not not reproduce it...
So you can close the issue for now ;)
