### ISSUE TITLE
Request: Possibility to format numerical sensor data

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#88]
It would be nice if it were possible to cut-off the displayed sensor values at a user defined number of decimals. Rounding would be even better, but not a necessity for me. 
![capture](https://cloud.githubusercontent.com/assets/7747627/12221617/e40a33ce-b7a2-11e5-95d4-cf8255718d5e.PNG)

**Comment by vades** [comment]
Is already integrated
