### ISSUE TITLE
V2.2.1-rc3: This link does not work (404)

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#89]
![capture](https://cloud.githubusercontent.com/assets/7747627/12241995/b84037a8-b896-11e5-9271-e5acc1a167f2.PNG)

Tested with Firefox and Chrome

**Comment by pz1** [comment]
Just for the record I did test this again in FireFox with rc2.1.2-rc6. The URL sent to the browser looks like this
```
http://raspi2:8083/smarthome/\"/expert\"
```

**Comment by vades** [comment]
This link is removed from the widget
