### ISSUE TITLE
In Logical Rules modules can't choose on/off for relay in "List of switches"

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#9]
In Logical Rules I can't choose on or off status for relay in Action section.
![2015-06-05 18 45 47](https://cloud.githubusercontent.com/assets/2894860/8009683/1b5e2c32-0bb3-11e5-9ce2-191ed57c1da3.png)

After SAVE "on" or "off" unchecked

**Comment by PoltoS** [comment]
а какие данные при сохранении отправляются?

**Comment by ronie-z-wave** [comment]
the problem seems to be in module.json:

schema { ...
   action { ...
      switches { ...
            "status": {
	          "type": "number",
	          "required": true,
	          "enum": ["off", "on"]
           }
see also:
      locks: { ...
           "status": {
		"type": "number",
		"required": true,
		"enum": ["close", "open"]
}}}}

enum should be number or type should be string I think ...

**Comment by bytedreamer** [comment]
I've included a fix in my home-automation pull request. Changing type to 'integer' resolved the issue.

**Comment by PoltoS** [comment]
"type": "number"
should become
"type": "string"

Right?

**Comment by PoltoS** [comment]
59c253a

**Comment by bytedreamer** [comment]
String also works, just tested it on my own system.

**Comment by bytedreamer** [comment]
I reverted my change in the pull request. 

Can you review my other changes? Thanks

**Comment by ronie-z-wave** [comment]
Jup, we will review it.
