### ISSUE TITLE
v2.2.1-rc3: Cannot add email address to user

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#90]
While logged in as user admin, I can not add any email address.
![capture](https://cloud.githubusercontent.com/assets/7747627/12262258/13b20c5c-b927-11e5-9e32-12122d806f89.PNG)

See also forum http://forum.z-wave.me/viewtopic.php?f=3422&t=22706

**Comment by ronie-z-wave** [comment]
Unfortunately it seems that adding a new user doesn't check if the given email adress does alredy exist. I'll change that ASAP.

Meanwhile please check your users and go for sure that they have different email adresses.

Btw. as admin user you are allowed to change/reset users login and password so you don't necessarily need to add an email for each of them ;)

See also my answer http://forum.z-wave.me/viewtopic.php?f=3422&t=22706&p=60535#p60535
