### ISSUE TITLE
v2.1.1-rc6 Login problem after upgrade

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#95]
In some cases there is a login problem after upgrade to RC6. I experienced it on one machine, but another went OK. This morning someone else on the forum confimed this.
See http://forum.z-wave.me/viewtopic.php?f=3422&t=22849

**Comment by vades** [comment]
Can you please provide more information about the problem?
Browser name/version, screenshot, console log etc. I have read post in forum and tested in:
- Chrome - OK
- Firefox - OK
- IE - does not wok - known problem with SCRIPT7002: XMLHttpRequest

**Comment by pz1** [comment]
My problem occurred with (almost) latest versions of Firefox, Chrome, Opera on RaspberyPi B which had v2.1.2-rc4. The ugrade did work on RaspberryPi 2. The failing installation was on Wheezy:

Linux raspberrypi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux
Linux raspi2 4.1.13-v7+ #826 SMP PREEMPT Fri Nov 13 20:19:03 GMT 2015 armv7l GNU/Linux

Can't make a screenshot, because I only see a sub-second flash of the login screen.

I can send compressed log of yesterday by email. Problem occured around [2016-02-02 20:22:21.168] 
I did keep the failed z-way-server directory. Can make that available if you need it

**Comment by pierre2302** [comment]
Impossible for me to connect me, I do not have time to become identified.

I have a raspi 2

Linux raspi2 4.1.16-v7+ #832 SMP Sun Jan 24 12:57:43 GMT 2016 armv7l

**Comment by ronie-z-wave** [comment]
Do you have tried to clean the browsers cache? 

Are ther errors in the browsers devlopers console? F12 - Network / Console

And you both are using wheezy on the affecting system?

**Comment by pz1** [comment]
> And you both are using wheezy on the affecting system?

For me it is wheezy on the affected system, Jessie on the non problematic.
I did explicitly clean the browers. Because I have reverted my machine to rc4 I can't test at the moment. (Where do you want me to send the log? And are you interested in a copy of the failing z-way-server directory as I mentioned?)

**Comment by pierre2302** [comment]
Console: 

`---------- ERROR: ---------- Object {data: "", status: 0, config: Object, statusText: ""}(anonymous function) @ build.js:7574logError @ build.js:9562responseError @ build.js:8600w @ build.js:7583w @ build.js:7583w @ build.js:7583(anonymous function) @ build.js:7584h.$eval @ build.js:7595h.$digest @ build.js:7592h.$apply @ build.js:7595m @ build.js:7554w @ build.js:7559B.onreadystatechange @ build.js:7561
build.js:7574 
---------- ERROR: ---------- Object {data: "", status: 0, config: Object, statusText: ""}(anonymous function) @ build.js:7574logError @ build.js:9562responseError @ build.js:8600w @ build.js:7583w @ build.js:7583w @ build.js:7583(anonymous function) @ build.js:7584h.$eval @ build.js:7595h.$digest @ build.js:7592h.$apply @ build.js:7595m @ build.js:7554w @ build.js:7559B.onreadystatechange @ build.js:7561
Navigated to http://192.168.1.100:8083/smarthome/
build.js:7574 
 `

Network:
![sans titre](https://cloud.githubusercontent.com/assets/17046610/12793610/b52fa58a-cab1-11e5-87a1-402385300f43.jpg)

**Comment by pz1** [comment]
Did an upgrade again this evening with v2.2.1-rc6 (not the one from yesterday but from this afternoon (foei!)
Did not see much on the F12 console. Things were flashing away quickly. Could pnly catch this
![capture](https://cloud.githubusercontent.com/assets/7747627/12795053/870bccae-cab8-11e5-9d17-c0447f128af2.PNG)

As you can see the controller is nicely capturing updates from Fibaro FUS.
Also in the network view I haven't seen anything happening until the login screen had disappeared.

**Comment by ronie-z-wave** [comment]
@pz1 please send it to nir@zwave.eu

**Comment by pz1** [comment]
I have answered via email. (if appropriate I wil update status here and on the forum)

**Comment by emilp333** [comment]
If seems to have something to do with the autologin. It first started for me after i pushed the logout button. Now I just see the loginscreen flashing by and then it gets me logged in but with no rights.
The remember me button is not ticked.
Can I manually turn off this feature?

**Comment by pz1** [comment]
> Can I manually turn off this feature?

Yes you can but than you have to remove all users of the type **anonymous**. 
I did post the work-around I got from Niels on the [forum](http://forum.z-wave.me/viewtopic.php?f=3422&t=22849&p=60818#p60818).

**Comment by pz1** [comment]
With the release of v2.2.1-rc7 this problem has been solved
