### ISSUE TITLE
Impossible to get login screen if local or anonymous user is present in rc6

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/zwave-smarthome#96]
Add local or anonymous and try to access SH UI (from local or any host correspondingly). You will not be able to logout nor to login as admin. This worked before in rc3.

This is important to fix before release.

![403 - local](https://cloud.githubusercontent.com/assets/3664383/12828282/f1eb58d2-cb94-11e5-9e34-6d858fdc001c.png)

**Comment by ronie-z-wave** [comment]
I'll check it.

think that is why you can now pass through https://github.com/Z-Wave-Me/zwave-smarthome/issues/79

You remember we've implemented that changes last time. Think thequestion is why the local user is logged in as anonymous or why he hasn't full admin rights.

Hope that my memory is correct that originally the the user should be logged in automatically if he is accessing from local - cause HA backend seems to work like that.

**Comment by pz1** [comment]
Could be related with https://github.com/Z-Wave-Me/zwave-smarthome/issues/95 as well?

**Comment by ronie-z-wave** [comment]
Thats possible. We're working on it.

**Comment by emilp333** [comment]
Is it possible to manually turn off this feature as a workaround meantime?
