### ISSUE TITLE
Feature request: Sort function in Online Apps

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/zwave-smarthome#97]
It would be nice to have a sort function for the Online Apps, like the one in http://raspIP:8083/smarthome/#/elements. Makes it easier to spot new/updated modules

**Comment by vades** [comment]
We are going to build this functionality in soon

**Comment by pz1** [comment]
thanks

**Comment by vades** [comment]
Will be in v2.2.2

**Comment by pz1** [comment]
Yes; checked with 2.2.2-rc4. thanks
