### ISSUE TITLE
Little bit edits and mobile ui will be petfect

### ISSUE THREAD

**Issue by aivs** [Z-Wave-Me/zwave-smarthome#98]
Desktop version of smarthome ui looks very good!
Some fixes and mobele ui will look good too!
At this moment top and bottom bars are big, the buttons are not in their places, widgets very big.

![image](https://cloud.githubusercontent.com/assets/2894860/12900328/cc636fca-cec6-11e5-826b-b36d33762a16.png)

**Comment by zwave-mke** [comment]
should be fixed with 2.2.1
